### ISSUE TITLE
[C++] Change Acero Aggregate output order

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32897] opened 2022-09-09 02:38 UTC
At the moment Acero Aggregates output contains aggregate fields followed by key fields. In Substrait this is the other way around. Also, it is not necessary to keep this static and use a project node to fulfill the requirement. It is rather important to modify this order and update the corresponding test cases. 

**Reporter**: [Vibhatha Lakmal Abeykoon](https://issues.apache.org/jira/browse/ARROW-17656) / @vibhatha

<sub>**Note**: *This issue was originally created as [ARROW-17656](https://issues.apache.org/jira/browse/ARROW-17656). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by westonpace** [comment] 2023-01-11 20:51
Closing as a duplicate of #33616

**Closed by westonpace** 2023-01-11 20:51 UTC
Labels: Type: enhancement, Component: C++
