### ISSUE TITLE
ARROW_HIVESERVER2

### ISSUE THREAD

**Issue by albertoRamon** [apache/arrow#2534] opened 2018-09-10 09:20 UTC
Hello 

Activate, support for hive, generate exception in CMake:

> CMake Error at src/arrow/dbi/hiveserver2/[CMakeLists.txt:116](https://github.com/apache/arrow/blob/a42d4bf1b0cef37849be0b019c34c96bf56a62f9/cpp/src/arrow/dbi/hiveserver2/CMakeLists.txt#L116) (set_property):
>   set_property could not find TARGET hiveserver2-test.  Perhaps it has not
>   yet been created

```
RUN cmake                                \
      -DARROW_HIVESERVER2=ON             \
      -DCMAKE_BUILD_TYPE=Release         \
      -DARROW_BUILD_TESTS=OFF            \
      .
```

**Comment by wesm** [comment] 2018-09-10 12:55
@albertoRamon this is the 4th GitHub issue you've opened in the last 24 hours -- can you please use JIRA going forward to report problems or feature requests? You'll be saving the maintainers like me time. Thanks

**Comment by albertoRamon** [comment] 2018-09-10 13:06
No problem of course, 
I did not want to create JIRAS that were not validated as bugs

**Comment by wesm** [comment] 2018-09-10 13:09
Right in this case, "Building with ARROW_HIVESERVER2=ON without unit tests disabled fails" is definitely a bug. This code only just landed in the codebase so it will need some work before being production-ready. If you feel even 20% confidence that something is a bug I would prefer that it go on JIRA and be resolved as "Not A Bug". 

We have GitHub issues available mostly to capture information from people who are unfamiliar with Apache projects

**Closed** 2018-09-10 14:06 UTC
