### ISSUE TITLE
[C++] Standardize aggregation column order

### ISSUE THREAD

**Issue by rtpsw** [apache/arrow#34930] opened 2023-04-06 12:42 UTC
### Describe the enhancement requested

Change aggregation column order to segment-keys then keys then aggregates.

### Component(s)

C++

**Comment by rtpsw** [comment] 2023-04-06 12:42
cc @westonpace @icexelloss

**Comment by icexelloss** [comment] 2023-04-06 14:09
This is a dup of https://github.com/apache/arrow/issues/34908

I am in favor of using #34908 because it has a bit more explanation in it.

**Comment by westonpace** [comment] 2023-04-11 16:17
Duplicate of #34908

**Closed** 2023-04-11 16:17 UTC
Labels: Type: enhancement, Component: C++
