### ISSUE TITLE
[Release] Automatize source verification task submission

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30934] opened 2022-01-25 22:47 UTC
The workflow would look like this:
```Java

git push -u apache release-<version>
git push -u apache release-<version>-rc<rc-number>
git push -u apache apache-arrow-<version>

dev/release/02-source.sh <version> <rc-number>
dev/release/03-source-verify.sh <version> <rc-number>
```

Where `03-source-verify.sh` would create a pull request and submit crossbow source verification tasks by either:
a. placing a github comment triggering the comment bot 
b. calling crossbow locally then placing a comment to the PR using the same `archery.crossbow.CommentReport` class

I'd suggest to use `gh` cli tool for implementation.

The resulting PR should look like this https://github.com/apache/arrow/pull/12262

Opinions @kou?

**Reporter**: [Krisztian Szucs](https://issues.apache.org/jira/browse/ARROW-15456) / @kszucs

<sub>**Note**: *This issue was originally created as [ARROW-15456](https://issues.apache.org/jira/browse/ARROW-15456). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment] 2023-01-11 04:26
Duplicate of #32012

**Closed** 2023-01-11 04:27 UTC
Labels: Type: enhancement, Component: Developer Tools
