### ISSUE TITLE
[Python] 17.0.0 wrongly installs multiple stray directories into site-packages

### ISSUE THREAD

**Issue by mgorny** [apache/arrow#43299] opened 2024-07-17 12:22 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

```
$ pip install pyarrow
Collecting pyarrow
  Downloading pyarrow-17.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting numpy>=1.16.6 (from pyarrow)
  Using cached numpy-2.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Downloading pyarrow-17.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (39.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 11.0 MB/s eta 0:00:00
Using cached numpy-2.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.0 MB)
Installing collected packages: numpy, pyarrow
Successfully installed numpy-2.0.0 pyarrow-17.0.0
$ ls .venv/lib/python3.12/site-packages/
benchmarks     examples  numpy-2.0.0.dist-info  pip                   pyarrow                   scripts
cmake_modules  numpy     numpy.libs             pip-24.1.2.dist-info  pyarrow-17.0.0.dist-info
```

Note that it wrongly installed `benchmarks`, `cmake_modules`, `examples` and `scripts` as top-level Python packages.

### Component(s)

Python

**Comment by raulcd** [comment] 2024-07-18 14:53
Hi,

Thanks for reporting. It seems we added this bug when migrating from setup.py to pyproject.toml

**Comment by timkpaine** [comment] 2024-07-19 16:28
duplicate of https://github.com/apache/arrow/issues/43280

**Comment by jorisvandenbossche** [comment] 2024-09-05 07:56
Issue resolved by pull request 43325
https://github.com/apache/arrow/pull/43325

**Closed by jorisvandenbossche** 2024-09-05 07:56 UTC
Labels: Type: bug, Component: Python, Priority: Blocker, backport-candidate

**Comment by mgorny** [comment] 2024-09-05 08:45
Thanks!
