### ISSUE TITLE
ModuleNotFoundError: No module named 'pyarrow.lib'

### ISSUE THREAD

**Issue by TheAnkurGoswami** [apache/arrow#11897] opened 2021-12-08 09:45 UTC
I am using `pyarrow==5.0.0` on `python 3.8` and facing this issue here. 

<img width="1193" alt="Screenshot 2021-12-08 at 3 10 31 PM" src="https://user-images.githubusercontent.com/39483475/145185461-25124c71-7f90-4d7a-8b86-65653196f787.png">

Inside the pyarrow directory, i'm seeing only `lib.pxd` and `lib.pyx`.

**Comment by kszucs** [comment] 2021-12-08 11:11
How did you install pyarrow?

**Comment by kszucs** [comment] 2021-12-08 11:27
What does `pip list` say?

Seems like it loads a local checkout of pyarrow: `~/Documents/pyarrow/__init__.py`. Could you try to import pyarrow from outside the pyarrow directory?

**Comment by TheAnkurGoswami** [comment] 2021-12-08 11:48
It seems to work inside terminal.

![image](https://user-images.githubusercontent.com/39483475/145203468-47760c56-263c-4a81-abce-6c97f2a55810.png)

**Comment by kszucs** [comment] 2021-12-08 11:50
Thanks @TheAnkurGoswami! I'm going to close the issue then.

**Closed by kszucs** 2021-12-08 11:50 UTC

**Comment by TheAnkurGoswami** [comment] 2021-12-08 12:18
It's not working for ipython notebooks. Any idea on that?

**Comment by TeddyH** [comment] 2023-02-17 04:57
I does not seems to be resolved, why is it closed?

**Comment by kou** [comment] 2023-02-20 02:44
@TeddyH If you still have the same issue, could you open a new issue with a description how to reproduce this issue?
