### ISSUE TITLE
[Java] Nullability of struct child vectors not preserved in TransferPair

### ISSUE THREAD

**Issue by FiV0** [apache/arrow#41686] opened 2024-05-16 09:58 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

When copying a struct vector via a transfer pair the nullability of the children is not preserved
```java
  @Test
  public void testMakeTransferPairPreserveNullability() {
    Field intField = new Field("int", FieldType.notNullable(MinorType.INT.getType()), null);
    Field structField = new Field("struct", FieldType.notNullable(Struct.INSTANCE), List.of(intField));
    FieldVector vec = structField.createVector(allocator);

    TransferPair tp = vec.getTransferPair(new Field("struct", FieldType.nullable(Struct.INSTANCE), List.of(intField)), allocator);
    tp.transfer();

    FieldVector res = (FieldVector) tp.getTo();

    // passes
    assertEquals(intField, vec.getField().getChildren().get(0));
    // fails
    assertEquals(intField, res.getField().getChildren().get(0));
  }
```
results in the failure 
```
Expected :int: Int(32, true) not null
Actual   :int: Int(32, true)
```

### Component(s)

Java

**Comment by tlm365** [comment] 2024-05-22 11:15
>Field structField = new Field("struct", FieldType.**notNullable**(Struct.INSTANCE), List.of(intField));
>FieldVector vec = structField.createVector(allocator);

>TransferPair tp = vec.getTransf>erPair(new Field("struct", FieldType.**nullable**(Struct.INSTANCE), List.of(intField)), allocator);

@FiV0 I don't think it's a bug. The bolding texts above are mismatched and that's the reason for the diff between `vec` and `res`.

**Comment by vibhatha** [comment] 2024-05-22 12:33
@tlm365 could you explain 

> The bolding texts above are mismatched

**Comment by tlm365** [comment] 2024-05-22 12:54
@vibhatha the Field he passed when create `vec` is **notNullable**:
Field structField = new Field("struct", FieldType.**notNullable**(Struct.INSTANCE), List.of(intField));
FieldVector vec = structField.createVector(allocator);

but **nullable** when pass to `getTransferPair`:
TransferPair tp = vec.getTransferPair(new Field("struct", FieldType.**nullable**(Struct.INSTANCE), List.of(intField)), allocator);

**Comment by vibhatha** [comment] 2024-05-22 13:31
> @vibhatha the Field he passed when create `vec` is **notNullable**: Field structField = new Field("struct", FieldType.**notNullable**(Struct.INSTANCE), List.of(intField)); FieldVector vec = structField.createVector(allocator);
> 
> but **nullable** when pass to `getTransferPair`: TransferPair tp = vec.getTransferPair(new Field("struct", FieldType.**nullable**(Struct.INSTANCE), List.of(intField)), allocator);

Oh I didn't catch that. Thanks @tlm365

**Comment by FiV0** [comment] 2024-05-22 14:43
This is about the nullability of the the child and not the struct.  Why should the nullability of a struct affect the nullability of its children?

**Comment by vibhatha** [comment] 2024-05-22 16:20
Hmm, @FiV0 I agree. I also tested it even with adding matching `nullability`, just for the sake of the argument. But still the issue is there.

**Comment by vibhatha** [comment] 2024-05-22 16:58
I am taking a look at this.

**Comment by vibhatha** [comment] 2024-05-22 17:35
I think the issue is [here](https://github.com/apache/arrow/blob/9ba9253e8527a7f3e2c6e47e631e278b8ca84e53/java/vector/src/main/codegen/templates/StructWriters.java#L298) `addVectorAsNullable` field is not properly set. This doesn't go to the buffer transfer level, from the type setting level, the nullability is inaccurately set AFAIU from debugging.

**Comment by vibhatha** [comment] 2024-05-22 17:44
I will make a draft PR shortly.

**Comment by lidavidm** [comment] 2024-05-24 04:01
Issue resolved by pull request 41785
https://github.com/apache/arrow/pull/41785

**Closed by lidavidm** 2024-05-24 04:01 UTC
Labels: Type: bug, Component: Java
