### ISSUE TITLE
[Python] `ArrowInvalid`: Could not convert `<pyarrow.Int32Scalar: 1>` with type `pyarrow.lib.Int32Scalar`: tried to convert to `int32`

### ISSUE THREAD

**Issue by randolf-scholz** [apache/arrow#36088] opened 2023-06-15 09:55 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

Was trying to convert some json-data to `list[int]`:

```python
import pyarrow as pa
import json

print(pa.__version__)
data = pa.array(["[1,2,3]", "[4,5,6]"], type=pa.string())
dtype = pa.list_(pa.int32())


def convert_py_list(x:pa.StringScalar) -> list[int]:
    return json.loads(x.as_py())

def convert_pa_list(x:pa.StringScalar) -> list[pa.Scalar]:
    return pa.scalar(json.loads(x.as_py()), type=dtype)

pa.array([convert_py_list(x) for x in data], type=dtype)  # ✔
pa.array([convert_pa_list(x) for x in data], type=dtype)  # ✘ ArrowInvalid
```

pyarrow version 12.0.1

### Component(s)

Python

**Comment by AlenkaF** [comment] 2023-06-15 12:56
`convert_pa_list` returns a list of pyarrow scalars (`ListScalars`) comparing to a list of lists:
```python
>>> [convert_py_list(x) for x in data]
[[1, 2, 3], [4, 5, 6]]
>>> [convert_pa_list(x) for x in data]
[<pyarrow.ListScalar: [1, 2, 3]>, <pyarrow.ListScalar: [4, 5, 6]>]
```

Currently `pa.array` constructor doesn't except pyarrow scalars, see: https://github.com/apache/arrow/issues/21761
We are currently working on this feature and I hope it will get added to 13.0.0 release.

**Comment by jorisvandenbossche** [comment] 2023-06-15 18:14
Closing as a duplicate of https://github.com/apache/arrow/issues/21761

**Closed by jorisvandenbossche** 2023-06-15 18:14 UTC
Labels: Type: bug, Component: Python
