### ISSUE TITLE
[Dev] Add unit tests for merge script

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#33692] opened 2023-01-16 11:28 UTC
### Describe the enhancement requested

The merge script should probably have basic unit tests to avoid issues and potential regressions such as #33687.

This can simply be an embedded unit test case.

### Component(s)

Developer Tools

**Comment by assignUser** [comment] 2023-02-21 03:25
Duplicate of #14802

**Closed** 2023-02-21 03:25 UTC
Labels: Type: enhancement, Component: Developer Tools
