### ISSUE TITLE
[Java] ArrowFlightPreparedStatement is missing dynamic parameters

### ISSUE THREAD

**Issue by dafeiw** [apache/arrow#35536] opened 2023-05-10 17:12 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

Hi Sir/Madam,

I noticed that ArrowFlightPreparedStatement doesn't have the dynamic parameters from flight server. (for example, `SELECT * FROM where f1 = ? or f2 = ?`)
[ArrowFlightPreparedStatement#createNewPreparedStatement](https://github.com/apache/arrow/blob/eaa1a1ea74e2b37020e0133f1460cb251e5f4974/java/flight/flight-sql-jdbc-core/src/main/java/org/apache/arrow/driver/jdbc/ArrowFlightPreparedStatement.java#L76)

This method only populates `signature.columns`  and doesn't populate `signature.parameters`, the client side couldn't do `preparedStmt.setByte(1, 0)`

Could you verify if it's a bug? 

### Component(s)

Java

**Comment by lidavidm** [comment] 2023-05-10 17:13
Duplicate of https://github.com/apache/arrow/issues/33475 I believe?

**Closed** 2023-11-04 17:01 UTC
Labels: Type: bug, Component: Java
