### ISSUE TITLE
AttributeError: module 'pyarrow.lib' has no attribute '_Weakrefable'

### ISSUE THREAD

**Issue by bhargav-inthezone** [apache/arrow#10502] opened 2021-06-10 09:42 UTC
hey !,
I'm working kaggle notebooks for a competition 

!pip install vaex  ## sucessfully installed

import vaex
print(vaex.__version__)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-2d4bdef9460d> in <module>
----> 1 import vaex
      2 import vaex.ml
      3 print(vaex.__version__)

/opt/conda/lib/python3.7/site-packages/vaex/__init__.py in <module>
     39 import six
     40 
---> 41 import vaex.dataframe
     42 import vaex.dataset
     43 from vaex.functions import register_function

/opt/conda/lib/python3.7/site-packages/vaex/dataframe.py in <module>
     15 import threading
     16 import six
---> 17 import vaex.utils
     18 # import vaex.image
     19 import numpy as np

/opt/conda/lib/python3.7/site-packages/vaex/utils.py in <module>
     24 
     25 from .json import VaexJsonEncoder, VaexJsonDecoder
---> 26 import vaex.file
     27 
     28 

/opt/conda/lib/python3.7/site-packages/vaex/file/__init__.py in <module>
     12 
     13 import pyarrow as pa
---> 14 import pyarrow.fs
     15 
     16 import vaex.file.cache

/opt/conda/lib/python3.7/site-packages/pyarrow/fs.py in <module>
     22 from pyarrow.util import _is_path_like, _stringify_path
     23 
---> 24 from pyarrow._fs import (  # noqa
     25     FileSelector,
     26     FileType,

/opt/conda/lib/python3.7/site-packages/pyarrow/_fs.pyx in init pyarrow._fs()

AttributeError: module 'pyarrow.lib' has no attribute '_Weakrefable'

**Comment by edponce** [comment] 2021-06-11 05:11
There are several [pyarrow files](https://github.com/apache/arrow/tree/master/python/pyarrow) (.pyx) that make use of `_Weakrefable` but do not import it explicitly and instead use `from pyarrow.lib cimport *`. `_Weakrefable` is privately defined (underscore) in [pyarrow.lib.pyx](https://github.com/apache/arrow/blob/master/python/pyarrow/lib.pxd#L34-L35). I can think of the following solutions:
1. (Recommended) Change `from pyarrow.lib cimport *` to list the explicit objects including `_Weakrefable` as in [_json.pyx](https://github.com/apache/arrow/blob/master/python/pyarrow/_json.pyx#L25)
2. Expose `_Weakrefable` publicly in `lib.pxd` with `__all___`

Maybe there is another workaround because it is strange that [other files](https://github.com/apache/arrow/blob/master/python/pyarrow/_compute.pyx) that use `_Weakrefable` do not import it explicitly and do not trigger this error.

**Comment by edponce** [comment] 2021-06-11 05:53
Please create a JIRA issue. Arrow uses JIRA to track/resolve issues. If you need help, feel free to ask.

**Comment by edponce** [comment] 2021-06-14 21:30
@bhargav-inthezone Kaggle notebook [installs latest pyarrow by default](https://github.com/Kaggle/docker-python/blob/main/Dockerfile#L347) but it seems the Docker image was created with Arrow 3.0.0. What version of Arrow do you have installed? Does the issue persists with Arrow 4.0.1?
I installed ``vaex`` in local Jupyter notebook and Google Colab notebook and it works fine. I have not been able to test in Kaggle notebook as I do not have an active account (...yet).

**Comment by bhargav-inthezone** [comment] 2021-06-15 03:49
I had to uninstall pyarrow before installing Vaex before but I  think kaggle fixed the problem. Now its working with installing just Vaex in the notebook

**Comment by jorisvandenbossche** [comment] 2021-06-15 12:14
> I can think of the following solutions:

@edponce I _assume_ this is actually an installation that somehow for some reason got messed up (eg not properly built), and not something to fix in pyarrow.

Since the problem now went away, I think we can close this issue? (or @bhargav-inthezone can you still reproduce the original error message?)

**Closed by jorisvandenbossche** 2021-06-15 12:14 UTC
