### ISSUE TITLE
Unable to read a parquet file 

### ISSUE THREAD

**Issue by alokgogate** [apache/arrow#2192] opened 2018-06-29 13:14 UTC
I am unable to read a parquet file created by converting a csv to parquet using yarrow (0.9.0). This is the error I get 
ArrowIOError                              Traceback (most recent call last)
<timed exec> in <module>()

~/anaconda3/lib/python3.6/site-packages/pyarrow/parquet.py in read_table(source, columns, nthreads, metadata, use_pandas_metadata)
    937             return fs.read_parquet(source, columns=columns, metadata=metadata)
    938 
--> 939     pf = ParquetFile(source, metadata=metadata)
    940     return pf.read(columns=columns, nthreads=nthreads,
    941                    use_pandas_metadata=use_pandas_metadata)

~/anaconda3/lib/python3.6/site-packages/pyarrow/parquet.py in __init__(self, source, metadata, common_metadata)
     62         self.reader = ParquetReader()
     63         source = _ensure_file(source)
---> 64         self.reader.open(source, metadata=metadata)
     65         self.common_metadata = common_metadata
     66         self._nested_paths_by_prefix = self._build_nested_paths()

_parquet.pyx in pyarrow._parquet.ParquetReader.open()

error.pxi in pyarrow.lib.check_status()

ArrowIOError: Invalid parquet file. Corrupt footer.

code:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import numpy as np

table = pq.read_table('big_file.parquet')

**Comment by xhochy** [comment] 2018-06-29 13:53
Can you provide a minimal reproducible example? https://stackoverflow.com/help/mcve

**Comment by wesm** [comment] 2018-07-09 20:59
Closing for now. @alokgogate if you can provide a reproducible example or any additional information to help us debug, please open a JIRA with the bug report.

**Closed by wesm** 2018-07-09 20:59 UTC

**Comment by BardiaAfshin** [comment] 2019-03-04 23:08
I'm loading a dataframe that has been created via pyspark  version 2.2.1 and saved in parquet format, I'm getting this very same error. What's the fix?

**Comment by xhochy** [comment] 2019-03-04 23:29
@BardiaAfshin Can you provide a minimal reproducible example? https://stackoverflow.com/help/mcve

**Comment by alokgogate** [comment] 2019-03-05 05:14
Downgrading to pyarrow version 0.8.0 worked for me.

**Comment by BardiaAfshin** [comment] 2019-03-05 17:37
@alokgogate that's interesting because I thought this is a memory related issue. I did a top command on the system and saw that loading a 1 gig file was taking up the memory space quickly. I loaded the parquet structure in a much smaller sample set of 12 MB and it worked fine. I will try to goto your current version. Also for the record the version I'm using now is 

``` pip freeze | grep pyarrow
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pyarrow==0.12.1```

**Comment by BardiaAfshin** [comment] 2019-03-05 17:39
Also, I looked that you can do buffering when reading a file using something called a ```NativeFile``` object? but didn't find any sample code on how todo.

**Comment by mckeown12** [comment] 2019-08-19 20:33
I'm experiencing a similar issue.  I'm running a simple flask app in Kubernetes which reads in parquet files from S3 and repeats their content to some frontend.  Relevant user code:
```python
pq.ParquetDataset('s3://mybucket/filename.parquet', filesystem=fs).read_pandas().to_pandas() 
```
If I run with limited memory (4Gb or less) I get the traceback:
```python
File "/usr/local/lib/python3.6/site-packages/pyarrow/parquet.py", line 130, in __init__ 
self.reader.open(source, use_memory_map=memory_map, metadata=metadata) 
File "pyarrow/_parquet.pyx", line 655, in pyarrow._parquet.ParquetReader.open 
File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status 
pyarrow.lib.ArrowIOError: Invalid parquet file. Corrupt footer. 
```
Similar to what @BardiaAfshin noted, if I increase the Kubernetes pod's available from 4Gi to 8Gi, everything works fine. 

The parquet files I'm reading in are only about 100KB so 8 gigs of ram feels excessive.

Another puzzling detail: Even with limited memory, if I ssh into the kubernetes pod I am able to make the same request in an ipython session without problem.  

I know this is far from self-contained or minimal, but If I get to the heart of the issue, I'll update.

**Comment by AlexMilman** [comment] 2019-12-24 13:53
Using pandas 0.24.2 and pyarrow 0.15.1 issue is still happening.
I'm writing to S3 with the command:
`df.to_parquet(s3_file_path, compression='snappy')`
But when I try to read it using:
`pd.read_parquet(s3_file_path, engine='pyarrow')`
I get the error:
```
---------------------------------------------------------------------------
ArrowIOError                              Traceback (most recent call last)
<ipython-input-15-530f7df702c9> in <module>()
      1 import pandas as pd
----> 2 data = pd.read_parquet('s3://ww-stage/insurance/features/20181201/part-00000.snappy.parquet', engine='pyarrow')

/mnt/xvdb/anaconda3/lib/python3.6/site-packages/pandas/io/parquet.py in read_parquet(path, engine, columns, **kwargs)
    280         ``io.parquet.engine`` is used. The default ``io.parquet.engine``
    281         behavior is to try 'pyarrow', falling back to 'fastparquet' if
--> 282         'pyarrow' is unavailable.
    283     columns : list, default=None
    284         If not None, only these columns will be read from the file.

/mnt/xvdb/anaconda3/lib/python3.6/site-packages/pandas/io/parquet.py in read(self, path, columns, **kwargs)
    127         if should_close:
    128             try:
--> 129                 path.close()
    130             except:  # noqa: flake8
    131                 pass

/mnt/xvdb/anaconda3/lib/python3.6/site-packages/pyarrow/parquet.py in read_table(source, columns, use_threads, metadata, use_pandas_metadata, memory_map, read_dictionary, filesystem, filters, buffer_size)
   1277                          read_dictionary=read_dictionary,
   1278                          memory_map=memory_map,
-> 1279                          buffer_size=buffer_size)
   1280     return pf.read(columns=columns, use_threads=use_threads,
   1281                    use_pandas_metadata=use_pandas_metadata)

/mnt/xvdb/anaconda3/lib/python3.6/site-packages/pyarrow/parquet.py in __init__(self, source, metadata, common_metadata, read_dictionary, memory_map, buffer_size)
    135         self.reader.open(source, use_memory_map=memory_map,
    136                          buffer_size=buffer_size,
--> 137                          read_dictionary=read_dictionary, metadata=metadata)
    138         self.common_metadata = common_metadata
    139         self._nested_paths_by_prefix = self._build_nested_paths()

/mnt/xvdb/anaconda3/lib/python3.6/site-packages/pyarrow/_parquet.pyx in pyarrow._parquet.ParquetReader.open()

/mnt/xvdb/anaconda3/lib/python3.6/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowIOError: Invalid parquet file. Corrupt footer.

```

**Comment by wesm** [comment] 2019-12-24 18:47
Can you please open a JIRA issue if you have a minimally-reproducible example? We don't track issues or provide help here.

**Comment by AlexMilman** [comment] 2019-12-25 10:05
> Can you please open a JIRA issue if you have a minimally-reproducible example? We don't track issues or provide help here.

Sorry, the issue is reproducible with my data, which I cannot provide.
Don't you have any solution for an issue that exists for so long, and has been reported so many times?
https://stackoverflow.com/questions/50688326/pandas-read-parquet-throws-arrowioerror-on-partitioned-spark-table
https://www.bountysource.com/issues/67642366-how-to-append-to-parquet-file-periodically-and-read-intermediate-data-pyarrow-lib-arrowioerror-invalid-parquet-file-corrupt-footer
https://gitmemory.com/issue/apache/arrow/2192/469459479

**Comment by thanuj11** [comment] 2019-12-26 19:24
@wesm I get the same issue as @AlexMilman , especially when working with parquet files in s3 

steps I used:
1. used df.to_parquet() to convert data frame to parquet file
2. upload data to s3
3. tried reading the file from aws lambda using 
 PQ.ParquetDataset(s3_filepath,filesystem = s3fs).read_pandas.to_pandas()

It gives me **Invalid parquet file. Corrupt footer.: ArrowIOError**

**Comment by mckeown12** [comment] 2019-12-26 20:05
For what it's worth, in the same project I mentioned above, I was also experiencing this issue with inaccurate FILENOTFOUND errors coming from s3fs. 
 https://github.com/dask/s3fs/issues/253

Adding some try except blocks with `fsspec.filesystem('s3').invalidate_cache()` seems to have fixed both problems.  

It could be that invalidating the cache was just freeing memory, but I wonder if some cached data might be corrupting the footers.  Just a thought.

**Comment by nealrichardson** [comment] 2019-12-27 16:28
For what it's worth, that error message may be misleading and could just mean that the file (or other error response from S3) is not a Parquet file. It's been revised for clarity since 0.15: https://github.com/apache/arrow/pull/5811/files#diff-2d20597229806f20349e26d7c1841d2fR231-R233

**Comment by thanuj11** [comment] 2019-12-27 20:36
@AlexMilman, I did a small workaround and I am able to get rid of the invalid parquet file, corrupt footer issue. use the link below, I implemented solution-5 to read file from s3 it worked for me, now I am not getting invalid parquet file issues. I hope this will help you

**https://inneka.com/programming/python/how-to-read-a-list-of-parquet-files-from-s3-as-a-pandas-dataframe-using-pyarrow/** 

@mckeown12 thanks for the suggestion I did try disabling cache on s3 but I was not successful then I tried using another way to read the parquet file it worked.

@nealrichardson I think the issue is when using pq.ParquetDataset() to read file from s3 (eg: aws lambda), When I try to read parquet file in s3 from aws lambda only then I faced this issue, but there might be other scenarios too.

**Comment by AlexMilman** [comment] 2019-12-28 09:31
@thanuj11 I'm not sure why you think this solution will work for me. As I mentioned I have a single file (I wrote) which I'm trying to read back. The code is as simple as it gets:
I'm writing to S3 with the command:
`df.to_parquet(s3_file_path, compression='snappy')`
But get an error when I try to read it using:
`pd.read_parquet(s3_file_path, engine='pyarrow')`

There are no multiple files in play here...

**Comment by thanuj11** [comment] 2019-12-30 22:22
@AlexMilman I mean to say instead of reading directly from s3 path try using the below method it may work for you. 

obj = s3.get_object(Bucket=bucket_name, Key=key)
df = pd.read_parquet(io.BytesIO(obj['Body'].read()))

**I had the same problem when I give s3 file path to read_parquet but then I used the above code it worked for me.** 
I am not sure if it is helpful for you or not, but worth giving it a try.

**Comment by wesm** [comment] 2020-01-06 18:53
> Don't you have any solution for an issue that exists for so long, and has been reported so many times?

@AlexMilman as a developer-maintainer it can be extremely difficult to fix a bug for which there is no reproducible example. To assign blame to people who are unable to reproduce the problem for not fixing it seems unfair. We are also unpaid volunteers (by the people reporting the issues) so there is a limit to what kind of obligations we can have absent some kind of explicit economic relationship. Note that all of the people who are encountering the problem are free to submit pull requests also

**Comment by lmeyerov** [comment] 2020-02-29 21:53
@wesm  We've been experiencing these as well, it may be around needing to enforce a clean close for a flush? We don't have a clean repro yet.

```
try:
  ...
  writer.write_table(table)
  ...
except KeyboardInterrupt as e:
   writer.close()
```

**Comment by lmeyerov** [comment] 2020-02-29 21:53
(In this case, it's twitter -> pandas -> arrow -> write)

**Comment by wesm** [comment] 2020-03-02 17:08
I see. Can you open a JIRA issue and provide as much information as you can so the issue is tracked somewhere other than here?

**Comment by panasenco** [comment] 2021-12-15 07:36
I just resolved a similar error in my project today.

I am using [`pyarrow.parquet.write_table`](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_table.html) to write my Parquet file.

I was passing a native Python file object to the `where` parameter, which somehow caused the footer to never get written.

When I switched to using [PyArrow output streams](https://arrow.apache.org/docs/python/memory.html?highlight=osfile#output-streams) instead of native Python file objects, the footer got written correctly on stream close, which resolved the "corrupt footer" issue for me.
