### ISSUE TITLE
ds.write_dataset how to implement new data?

### ISSUE THREAD

**Issue by phpsxg** [apache/arrow#14837] opened 2022-12-05 08:58 UTC
When I am using pq.write_to_dataset ( existing_data_behavior='overwrite_or_ignore') is able to add data
Why is the use of ds.write_dataset ( existing_data_behavior = 'overwrite_or_ignore') an overlay?

```
df = pd.DataFrame({'one': [-1, 3, 2.5, 2.5, 2.5],
                   'two': ['foo', 'bar', 'baz', 'foo', 'foo'],
                   'three': [True, False, True, False, True],
                   'four': [datetime.date(2021, 1, 3), datetime.date(2021, 3, 1), datetime.date(2021, 1, 1),
                            datetime.date(2021, 3, 11), datetime.date(2021, 4, 1)]
                   },
                  index=list('abcde'))


table = pa.Table.from_pandas(df, preserve_index=True)
```

**pq.write_to_datase**
```
pq.write_to_dataset(table, root_path=root_path,
                    # existing_data_behavior='delete_matching',
                    existing_data_behavior='overwrite_or_ignore',
                    use_legacy_dataset=False
                    )
```

**ds.write_dataset**
```
ds.write_dataset(table, root_path,
                 # existing_data_behavior='delete_matching',
                 existing_data_behavior='overwrite_or_ignore',
                 format="parquet")
``

### Component(s)

Parquet, Python

**Comment by assignUser** [comment] 2022-12-05 12:11
Duplicate of #14834

**Closed by assignUser** 2022-12-05 12:11 UTC
Labels: Type: bug
