### ISSUE TITLE
[Python][CI] test_total_bytes_allocated fails on arm64 wheels for manylinux

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#36201] opened 2023-06-21 13:10 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

The following nightly jobs:

* [wheel-manylinux-2-28-cp38-arm64](https://github.com/ursacomputing/crossbow/actions/runs/5320333807/jobs/9633957240)
* [wheel-manylinux-2-28-cp39-arm64](https://github.com/ursacomputing/crossbow/actions/runs/5320321966/jobs/9633929863)
* [wheel-manylinux-2014-cp310-arm64](https://github.com/ursacomputing/crossbow/actions/runs/5320341397/jobs/9633976139)
* [wheel-manylinux-2014-cp39-arm64](https://github.com/ursacomputing/crossbow/actions/runs/5320322269/jobs/9633930458)

Have been failing lately with:

```
 =================================== FAILURES ===================================
__________________________ test_total_bytes_allocated __________________________

    def test_total_bytes_allocated():
>       assert pa.total_allocated_bytes() == 0
E       assert 1216 == 0
E        +  where 1216 = <built-in function total_allocated_bytes>()
E        +    where <built-in function total_allocated_bytes> = pa.total_allocated_bytes
```

### Component(s)

Continuous Integration, Python

**Comment by kou** [comment] 2023-06-21 21:12
#35728 may be related or duplicated.

**Comment by jorisvandenbossche** [comment] 2023-06-22 05:13
Duplicate of #35728

**Closed by jorisvandenbossche** 2023-06-22 05:13 UTC
Labels: Type: bug, Component: Python, Component: Continuous Integration, Priority: Blocker

**Comment by raulcd** [comment] 2023-06-22 09:07
thanks @kou @jorisvandenbossche I missed the original one!
