### ISSUE TITLE
[Python]read_parquet throw ArrowNotImplementedError if empty dataframe exists

### ISSUE THREAD

**Issue by wukan1986** [apache/arrow#12458] opened 2022-02-18 01:18 UTC
```python
import pandas as pd
import pyarrow as pa

print(pd.__version__)  # 1.4.1
print(pa.__version__)  # 7.0.0

dr = pd.date_range(start='2022-01-01', end='2022-01-10', freq='D')
df = pd.DataFrame(index=dr)
df['A'] = pd.to_datetime('today')
df['B'] = 1.0
df['C'] = 'a'
df['D'] = 2

df.head(1).to_parquet('b/0.parquet')  # not empty dataframe
df.to_parquet('b/1.parquet')
pd.read_parquet('b')  # pass

df.head(0).to_parquet('b/0.parquet')  # empty dataframe
pd.read_parquet('b')  # pyarrow.lib.ArrowNotImplementedError

```

```python
Traceback (most recent call last):
  File "D:/a.py", line 19, in <module>
    pd.read_parquet('b')  # pyarrow.lib.ArrowNotImplementedError
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\pandas\io\parquet.py", line 493, in read_parquet
    return impl.read(
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\pandas\io\parquet.py", line 240, in read
    result = self.api.parquet.read_table(
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\pyarrow\parquet.py", line 1996, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,
  File "D:\Users\Kan\miniconda3\envs\py38\lib\site-packages\pyarrow\parquet.py", line 1831, in read
    table = self._dataset.to_table(
  File "pyarrow\_dataset.pyx", line 323, in pyarrow._dataset.Dataset.to_table
  File "pyarrow\_dataset.pyx", line 2311, in pyarrow._dataset.Scanner.to_table
  File "pyarrow\error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 120, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Unsupported cast from string to null using function cast_null
```

**Comment by wjones127** [comment] 2022-02-18 01:42
Hi @wukan1986! Thank you for the bug report and the very clear reproducible example. 

This seems to happen because column C lost type information when converting from Pandas DataFrame to Arrow table (which happens inside of `to_parquet`.)

```python
pa.Table.from_pandas(df.head(0))
```

```
pyarrow.Table
A: timestamp[ns]
B: double
C: null
D: int64
__index_level_0__: timestamp[ns]
----
A: [[]]
B: [[]]
C: [0 nulls]
D: [[]]
__index_level_0__: [[]]
```

So those two parquet files have different schemas:

```python
import pyarrow.parquet as pq

print(pq.read_table(temp_dir + '/0.parquet').schema)
print(pq.read_table(temp_dir + '/1.parquet').schema)
```

```
A: timestamp[us]
B: double
C: null
D: int64
__index_level_0__: timestamp[us]
-- schema metadata --
pandas: '{"index_columns": ["__index_level_0__"], "column_indexes": [{"na' + 753
A: timestamp[us]
B: double
C: string
D: int64
__index_level_0__: timestamp[us]
-- schema metadata --
pandas: '{"index_columns": ["__index_level_0__"], "column_indexes": [{"na' + 755
```

I think this is a limitation of Pandas string columns, which just have `dtype: object`, so if the column is empty there is nothing to tell Arrow what type it is. The best way to work around this is to give the column a more specific type. Either the Pandas string type, the PyArrow string type, or the Categorical type would work well here.


```python
import pandas as pd
import pyarrow as pa
from tempfile import mkdtemp

print(pd.__version__)  # 1.4.1
print(pa.__version__)  # 7.0.0

dr = pd.date_range(start='2022-01-01', end='2022-01-10', freq='D')
df = pd.DataFrame(index=dr)
df['A'] = pd.to_datetime('today')
df['B'] = 1.0
df['C'] = 'a'
df['D'] = 2

# Any of these will work
# df['C'] = pd.Series(df['C'], dtype="string")
# df['C'] = pd.Series(df['C'], dtype="string[pyarrow]")
df['C'] = pd.Categorical(df['C'])
```

**Comment by wukan1986** [comment] 2022-02-18 02:26
Thank you very much.

Can pyarrow skip merge emtpy file when index length is 0?

**Comment by wukan1986** [comment] 2022-02-18 03:19
I found that,  first file is not empty dataframe, it is work.

```python
import pandas as pd
import pyarrow as pa

print(pd.__version__)  # 1.4.1
print(pa.__version__)  # 7.0.0

dr = pd.date_range(start='2022-01-01', end='2022-01-10', freq='D')
df = pd.DataFrame(index=dr)
df['A'] = pd.to_datetime('today')
df['B'] = 1.0
df['C'] = 'a'
df['D'] = 2

df.head(1).to_parquet('b/0.parquet')  # not empty dateframe
df.head(0).to_parquet('b/1.parquet')  # empty dateframe
df.head(0).to_parquet('b/2.parquet')  # empty dateframe
df.to_parquet('b/3.parquet')
pd.read_parquet('b')
```

**Comment by AlenkaF** [comment] 2022-02-18 13:05
You could also try to pass a schema to `to_parquet` if you know you have strings for certain columns:

```python
import pandas as pd
import pyarrow as pa

dr = pd.date_range(start='2022-01-01', end='2022-01-10', freq='D')
df = pd.DataFrame(index=dr)
df['A'] = pd.to_datetime('today')
df['B'] = 1.0
df['C'] = 'a'
df['D'] = 2

schema = pa.schema([
    pa.field('A', pa.timestamp('ns')),
    pa.field('B', pa.float64()),
    pa.field('C', pa.string()),
    pa.field('D', pa.int64())])

df.head(0).to_parquet('b/0.parquet', schema=schema)
df.to_parquet('b/1.parquet')
pd.read_parquet('b') 
                           A    B  C  D
0 2022-02-18 14:03:36.691288  1.0  a  2
1 2022-02-18 14:03:36.691288  1.0  a  2
2 2022-02-18 14:03:36.691288  1.0  a  2
3 2022-02-18 14:03:36.691288  1.0  a  2
4 2022-02-18 14:03:36.691288  1.0  a  2
5 2022-02-18 14:03:36.691288  1.0  a  2
6 2022-02-18 14:03:36.691288  1.0  a  2
7 2022-02-18 14:03:36.691288  1.0  a  2
8 2022-02-18 14:03:36.691288  1.0  a  2
9 2022-02-18 14:03:36.691288  1.0  a  2
```

See https://issues.apache.org/jira/browse/ARROW-14488

**Comment by jorisvandenbossche** [comment] 2022-05-19 15:23
I am going to close this issue, assuming the question has been answered (in general for empty pandas dataframes, pyarrow cannot always infer the proper types, and then supplying an explicit schema can help with that). Feel free to further respond or reopen if that was a wrong assessment.

**Closed by jorisvandenbossche** 2022-05-19 15:23 UTC
