### ISSUE TITLE
[CI][C++] Add a testing coverage tool

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#20067] opened 2022-01-12 11:00 UTC
It would be good to estimate what fraction of the code the tests cover. Using a tool such as [CodeCov](https://about.codecov.io) or [Coveralls](https://coveralls.io/) maybe helpful

**Reporter**: [Benson Muite](https://issues.apache.org/jira/browse/ARROW-15308) / @bkmgit
#### Related issues:
- [[TESTS] Add a testing coverage tool](https://github.com/apache/arrow/issues/30798) (fixes)
- [[C++] Organize tests in scalar_compare_test.cc](https://github.com/apache/arrow/issues/30829) (is depended upon by)

<sub>**Note**: *This issue was originally created as [ARROW-15308](https://issues.apache.org/jira/browse/ARROW-15308). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment] 2024-11-13 17:05
This is a duplicate of GH-31212

**Closed by pitrou** 2024-11-13 17:05 UTC
Labels: Type: enhancement, Component: Continuous Integration, Component: Developer Tools
