### ISSUE TITLE
[C++] Memory access out of bounds in arrow-1.0.0

### ISSUE THREAD

**Issue by luffy-zh** [apache/arrow#34329] opened 2023-02-24 11:18 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

Memory access is out of bounds at line array_nested.cc:78. There is no need to clear the bits of the final offset.

### Component(s)

C++

**Comment by westonpace** [comment] 2023-02-24 14:54
This was fixed in https://github.com/apache/arrow/pull/9801

We may patch the current release but we don't typically backport fixes to older releases.

**Comment by kou** [comment] 2023-02-24 20:40
Thanks for the report but I close this as duplicate of #27902.

**Closed by kou** 2023-02-24 20:40 UTC
Labels: Type: bug, Component: C++
