### ISSUE TITLE
[Python] Uploading nightly wheels to the scientific python nightly channel

### ISSUE THREAD

**Issue by jarrodmillman** [apache/arrow#40216] opened 2024-02-23 20:09 UTC
### Describe the enhancement requested

It looks like you already build nightly Python wheels:
- https://github.com/apache/arrow/blob/main/docs/source/developers/python.rst#installing-nightly-packages

Would you be interested/willing to upload nightly wheels to he [scientific-python nightly channel](https://anaconda.org/scientific-python-nightly-wheels) instead:
- https://anaconda.org/scientific-python-nightly-wheels/

This would make the wheels easier to discover by hosting them in a "standard" place. It will also make it easier for downstream projects to test against multiple packages, since they won't need to specify multiple locations in their CI scripts.

You can read more about why and how we are building / testing against nightly wheels here:
https://scientific-python.org/specs/spec-0004/

We also provide a GitHub action to upload and manage nightly builds:
https://github.com/scientific-python/upload-nightly-action/

We @matthewfeickert, @larsoner, @tupui are happy to help.

### Component(s)

Python

### Linked PRs

- https://github.com/apache/arrow/pull/43862
- https://github.com/apache/arrow/pull/43932
- https://github.com/apache/arrow/pull/43943

**Comment by jorisvandenbossche** [comment] 2024-02-27 13:36
cc @raulcd 

This sounds as an interesting idea to me. My understanding is that our nightly wheels are not "official" release artifacts anyway, so it shouldn't matter too much where it is hosted? (also not sure if the current hosting location is actually tied to the Apache foundation)

I suppose the main cost is the cost of switching for current users of this (and for them to first find out that the old link no longer gives them the latest packages, at the time we would decide to stop uploading there as well)

**Comment by matthewfeickert** [comment] 2024-03-25 04:56
:wave: @jorisvandenbossche Just wanted to see if the team had any further thoughts on this. Let us know if we can help answer any questions.

**Comment by raulcd** [comment] 2024-03-25 10:02
We probably could upload wheels to both places. In terms of discoverability we have to advise to users that the wheels provided are not official releases and should be used at their own risk. Similar to what we have at the documentation:
`These packages are not official releases. Use them at your own risk.`
This is because the Apache Release Policy (https://www.apache.org/legal/release-policy.html#what) says:

> During the process of developing software and preparing a release, various packages are made available to the developer community for testing purposes. Do not include any links on the project website that might encourage non-developers to download and use nightly builds, snapshots, release candidates, or any other similar package. The only people who are supposed to know about such packages are the people following the dev list (or searching its archives) and thus aware of the conditions placed on the package. If you find that the general public are downloading such test packages, then remove them.

I think we are ok publishing the nightly wheels under the scientific python nightly channel.

**Comment by matthewfeickert** [comment] 2024-03-25 16:40
> I think we are ok publishing the nightly wheels under the scientific python nightly channel.

Great! To move forward we need someone in the Arrow organization to do the following:

* [ ] Create an account on [Anaconda Cloud](https://anaconda.org/)
* [ ] Reply here with the link to your account (https://anaconda.org/rgommers)
* [ ] Make a new Anaconda Cloud API token with permissions described in https://scientific-python.org/specs/spec-0004/#process-for-adding-new-projects

![image](https://github.com/scientific-python/upload-nightly-action/assets/5142394/697ce89f-4a51-43d0-a26f-2493f4bdce34)

* [ ] Save the API token as a repo GitHub Actions secret named `ANACONDA_ORG_UPLOAD_TOKEN`
* [ ] Direct me (@matthewfeickert) to a `pyarrow` nightly wheel for me to upload to create the package in the registry
* [ ] Verify that I have added you to the [`pyarrow` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/pyarrow) on https://anaconda.org/scientific-python-nightly-wheels
* [ ] Verify that I have added the package `scientific-python-nightly-wheels/pyarrow` to the [`pyarrow` team "Group"](https://anaconda.org/scientific-python-nightly-wheels/groups/pyarrow)

If you'd also like to use the [`scientific/upload-nightly-action` GitHub Action](https://github.com/scientific-python/upload-nightly-action) please check out [the action repo's README](https://github.com/scientific-python/upload-nightly-action?tab=readme-ov-file#nightly-upload). If you need to collect wheels from different CI jobs, consider creating a new GitHub Actions workflow with logic similar to [`matplotlib`'s](https://github.com/matplotlib/matplotlib/blob/88d64e5f0cc82a050b840e61ac60e1081bb6d799/.github/workflows/nightlies.yml) or [`Awkward`'s](https://github.com/scikit-hep/awkward/pull/3012).

**Comment by kou** [comment] 2024-03-26 03:54
Could you add me https://anaconda.org/ktou/ to the `pyarrow` team "Group" too?

**Comment by matthewfeickert** [comment] 2024-03-26 04:06
@kou done. As soon as you generate an API token you can start uploading to https://anaconda.org/scientific-python-nightly-wheels/pyarrow. :+1: Let's leave this Issue open though until the first automated CI/CD upload passes.

**Comment by kou** [comment] 2024-03-27 06:22
Thanks! I confirmed that I'm a member of the group.

@assignUser We need to ask INFRA to set `ANACONDA_ORG_UPLOAD_TOKEN` secret to our GitHub Actions. Could you also join the group, generate your API token and ask INFRA to set `ANACONDA_ORG_UPLOAD_TOKEN`?

**Comment by matthewfeickert** [comment] 2024-03-27 08:00
> Could you also join the group, generate your API token and ask INFRA to set ANACONDA_ORG_UPLOAD_TOKEN?

@assignUser Can you also share your Anaconda Cloud account name so I can add you to the `pyarrow` group?

**Comment by assignUser** [comment] 2024-04-05 23:06
@matthewfeickert Sorry I missed the notifications :see_no_evil:  https://anaconda.org/assignuser

**Comment by matthewfeickert** [comment] 2024-04-05 23:25
@assignUser added. :+1:

**Comment by assignUser** [comment] 2024-04-06 02:02
I'll take care of adding the token with infra

**Comment by assignUser** [comment] 2024-04-09 00:35
See https://issues.apache.org/jira/browse/INFRA-25697

**Comment by assignUser** [comment] 2024-04-09 01:15
@kou infra just added the secret so we can create a workflow (will close the ticket once we can confirm it works)

**Comment by kou** [comment] 2024-04-09 05:40
Thanks!

**Comment by matthewfeickert** [comment] 2024-04-10 22:30
> INFRA will add the secret but with a `ARROW_` prefix for organizational reasons

That's totally fine. The secret name is arbitrary even if the GitHub Actions uploaded is used, but I just suggest a name to keep it simple for people. :+1:

**Comment by kou** [comment] 2024-04-11 02:05
OK. What is the next action then? We need to update our workflows?

**Comment by assignUser** [comment] 2024-04-11 03:13
@kou As far as I understand we need to create a workflow similiar to `r_nightly.yml` that collects the pyarrow wheels and then uploads them to the anaconda channel using the new secret.

**Comment by matthewfeickert** [comment] 2024-04-11 09:00
> we need to create a workflow similar to `r_nightly.yml` that collects the pyarrow wheels from crossbow and then uploads them to the anaconda channel using the new secret.

Yeah. https://github.com/apache/arrow/issues/40216#issuecomment-2018437734 has some linked examples.

**Comment by matthewfeickert** [comment] 2024-05-22 16:12
:wave: @kou @assignUser I just wanted to follow up on this to see if there are any questions on your end RE: getting deployments up.

**Comment by kou** [comment] 2024-05-23 02:46
@assignUser Can you work on this? Or should someone work on this?

**Comment by assignUser** [comment] 2024-05-23 02:48
@kou I won't get to it quickly but I can take a look 'soon'(tm), maybe @matthewfeickert would be interested in working on it? The way we generate the wheels is a bit complex but it seems you have looked into that already?

**Comment by matthewfeickert** [comment] 2024-05-23 03:59
@assignUser Realistically I don't have time at the moment, given that summer is peak everything time for academia.

**Comment by jorisvandenbossche** [comment] 2024-08-14 09:23
> As far as I understand we need to create a workflow similiar to `r_nightly.yml` that collects the pyarrow wheels from crossbow and then uploads them to the anaconda channel using the new secret.

For uploading the wheels, we currently have the `github_upload_gemfury` github actions macro, that is used to upload the built nightly wheels directly from the jobs building and testing them, for example at 

https://github.com/apache/arrow/blob/712cfe6d84bd344cfe57a1e4c791f8a4d052c76d/dev/tasks/python-wheels/github.linux.yml#L108

We could do this with a similar approach adding an extra macro to upload the wheels to anaconda.org?  
Or @assignUser is there a reason for (or advantage to) using an approach like `r_nightly.yml` collecting all artifacts and uploading from a run on this repo? (the file mention "Due to authorization requirements, this upload can't be done from the crossbow repository.", but is that because this one is syncing with nightlies.apache.org? Uploading to gemfury doesn't seem to have that issue)

**Comment by raulcd** [comment] 2024-08-28 10:03
I agree with @jorisvandenbossche , I am unsure why we can't upload those directly from the crossbow wheel jobs and we require to do something like the r_nightly. On that case the tokens should be added to crossbow instead of the arrow repo. I can try that. @matthewfeickert Can I be added to the https://anaconda.org/scientific-python-nightly-wheels/pyarrow group?

**Comment by matthewfeickert** [comment] 2024-08-28 10:10
> Can I be added to the https://anaconda.org/scientific-python-nightly-wheels/pyarrow group?

@raulcd Sure. What's your Anaconda Cloud username? Is it https://anaconda.org/raulcd ?

**Comment by raulcd** [comment] 2024-08-28 10:16
> @raulcd Sure. What's your Anaconda Cloud username? Is it https://anaconda.org/raulcd ?

Yes, sorry: https://anaconda.org/raulcd

**Comment by matthewfeickert** [comment] 2024-08-28 10:17
@raulcd done

![image](https://github.com/user-attachments/assets/b5f5a53b-e3d2-47c5-bbd5-e5a39bf5096f)

**Comment by raulcd** [comment] 2024-08-28 10:26
If I try to access that page (https://anaconda.org/scientific-python-nightly-wheels/groups/PyArrow) or the page to create a token (https://anaconda.org/scientific-python-nightly-wheels/settings/access)
I get:
![image](https://github.com/user-attachments/assets/31c78c8c-7932-4351-b1f9-f8c73015d143)
Even though if I check my groups I can see the pyarrow one:
![image](https://github.com/user-attachments/assets/95c21975-6617-411d-9685-86060ee95e8c)
Is there any other access that has to be granted?

**Comment by raulcd** [comment] 2024-08-28 12:21
> Ah yeah, you don't create tokens through the scientific python org account but your own personal account. c.f.

Thanks, I have added the token to the repo and will work on it. I was confused by the upload-nightly-action `README`: https://github.com/scientific-python/upload-nightly-action/blob/main/README.md#access-to-the-scientific-python-nightly-wheels-channel

**Comment by matthewfeickert** [comment] 2024-08-28 14:02
> Thanks, I have added the token to the repo and will work on it. I was confused by the upload-nightly-action `README`: https://github.com/scientific-python/upload-nightly-action/blob/main/README.md#access-to-the-scientific-python-nightly-wheels-channel

Ack! :scream: Sorry, that was a bad typo. Fixed now with https://github.com/scientific-python/upload-nightly-action/blob/a4a4ff84985afbf28e3320b3573708a9ae394a65/README.md?plain=1#L43 but thank you for catching that!

**Comment by assignUser** [comment] 2024-09-02 22:37
Issue resolved by pull request 43862
https://github.com/apache/arrow/pull/43862

**Comment by matthewfeickert** [comment] 2024-09-03 03:56
I haven't looked at this closely and will be offline tomorrow for travel but while there are files (`v18.0.0.dev236`) on the index (https://anaconda.org/scientific-python-nightly-wheels/pyarrow/files), their metadata isn't getting properly picked up:

```console
$ docker run --rm -ti python:3.12 /bin/bash
root@2131275711b3:/# python -m venv venv && . venv/bin/activate
(venv) root@2131275711b3:/# python -m pip index --pre --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple versions pyarrow
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
ERROR: No matching distribution found for pyarrow
(venv) root@2131275711b3:/# python -m pip install --pre --upgrade --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple pyarrow
Looking in indexes: https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
ERROR: Could not find a version that satisfies the requirement pyarrow (from versions: none)
ERROR: No matching distribution found for pyarrow
```

**Comment by jorisvandenbossche** [comment] 2024-09-03 08:34
I see the same issue. The wheels itself look fine though (also when downloaded and pointing pip directly to it, that installs fine). So wondering if this is something on the server side or related to how we upload them.

Now, the first nightly run of the packaging builds that will now automatically upload them still has to run (they should be scheduled shortly I think). So the current files were uploaded somewhere throughout the PR (although I wouldn't think this should make any difference).

**Comment by jorisvandenbossche** [comment] 2024-09-03 08:42
Ah, this is because we are uploading the wheels to the `dev` label, instead of `main`. 
Explicitly pointing to the equivalent url (`--index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/label/dev/simple`, as instructed by https://anaconda.org/scientific-python-nightly-wheels/pyarrow) does work.

All other packages are being uploaded to main (and the full channel is meant for nightly wheel, so there is no need to distinguish main vs dev, I suppose), so will correct that to also upload to main.

**Comment by jorisvandenbossche** [comment] 2024-09-03 08:53
Something else: we might also want to consider to _not_ upload the nightly sdist. While it can be useful to upload this _somewhere_, there are some drawbacks in uploading it the same index for the nightly wheels. 
Especially when some of the nightly wheel builds fail for whatever reason, but the sdist is uploaded, and then a downstream project installing pyarrow from the nightly wheels might get the sdist (which will almost always fail) as latest version instead of the wheel of the day(s) before (I think downstream projects could solve that by using `--prefer-binary` flag to pip, but that is easy to forget)

**Comment by raulcd** [comment] 2024-09-03 14:58
Some of the nightly wheels have also failed to upload similar to the failures that we found on the latest PR from @jorisvandenbossche :
[wheel-macos-monterey-cp310-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10679422709/job/29598609838)
[wheel-windows-cp310-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10679423193/job/29598612620)
[wheel-windows-cp313-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10679423270/job/29598612911)
[wheel-windows-cp39-amd64](https://github.com/ursacomputing/crossbow/actions/runs/10679423048/job/29598611596)
Those errors might have been temporary network errors but we should monitor and maybe add some retry mechanism to the upload if this is common.

**Comment by matthewfeickert** [comment] 2024-09-03 15:46
Quick comments as I'm in transit (sorry):

* yes, if you want the dev label please add that in addition to main.

c.f. https://github.com/scientific-python/upload-nightly-action/blob/b3d150d89b9500cd5623f211d6214f1d8b50fac5/action.yml#L21-L24 and https://github.com/scientific-python/upload-nightly-action/blob/b3d150d89b9500cd5623f211d6214f1d8b50fac5/cmd.sh#L44-L53

* In general we'd prefer to only upload wheels so that people using the index for testing don't accidentally run into situations in which they trigger a build from sdist.

**Comment by jorisvandenbossche** [comment] 2024-09-04 07:54
> * In general we'd prefer to only upload wheels so that people using the index for testing don't accidentally run into situations in which they trigger a build from sdist.

Opened a PR to remove the sdist uploading: https://github.com/apache/arrow/pull/43943

**Comment by raulcd** [comment] 2024-09-04 08:49
Issue resolved by pull request 43943
https://github.com/apache/arrow/pull/43943

**Comment by raulcd** [comment] 2024-09-04 08:50
With the latest changes I've closed the issue as done. Please re-open or open a new issue if any follow up is necessary.
Thanks @jorisvandenbossche for following this up!

**Closed by raulcd** 2024-09-04 08:49 UTC
Labels: Type: enhancement, Component: Python

**Comment by larsoner** [comment] 2025-02-24 15:53
There are no longer any Windows wheels up at https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/pyarrow/ , is this intentional? At least I think there used to be Windows wheels

**Comment by assignUser** [comment] 2025-02-24 16:11
Looks like the windows nightly builds have failed for a few days and the channel is removing old files?

**Comment by larsoner** [comment] 2025-02-24 18:15
Yeah I know there is some removal policy, I thought it was a month but I could be wrong (and it might also be per-project configurable, not sure!). A few days seems like too short a removal period in any case.

**Comment by matthewfeickert** [comment] 2025-02-24 18:46
> Yeah I know there is some removal policy, I thought it was a month but I could be wrong

It is 30 days (c.f. https://github.com/scientific-python/upload-nightly-action/blob/07ba11e3fcd43a475f9f56a9b06555aa2c621136/.github/workflows/remove-wheels.yml#L61-66)

> (and it might also be per-project configurable, not sure!).

Currently, no. There is a "never delete anything" option, but the only project that had a good use case for that no longer needs it.

**Comment by raulcd** [comment] 2025-02-24 18:57
From my understanding there is still a max number of wheels allowed too, right? Taking into account all our different wheels (macos arm + x86_64, manylinux_2014 and manylinux_2_28 both for arm + x86_64 for Python versions from 3.9 to 3.13) we get about ~6 days of wheels. See the oldest ones here: https://anaconda.org/scientific-python-nightly-wheels/pyarrow/files?page=4
The Windows nightly jobs have failed for slightly longer so they've just been removed.

**Comment by matthewfeickert** [comment] 2025-02-24 19:37
> From my understanding there is still a max number of wheels allowed too, right?

We don't impose a maximum number of artifacts. If any project takes up too much total storage we would look into how to reduce it, but the automatic removal workflow is meant to avoid this and also have "nightly" mean something relatively recent.

> Taking into account all our different wheels (macos arm + x86_64, manylinux_2014 and manylinux_2_28 both for arm + x86_64 for Python versions from 3.9 to 3.13) we get about ~6 days of wheels.

I assume you're just seeing that we also keep only the last 5 uploads by default:

https://github.com/scientific-python/upload-nightly-action/blob/07ba11e3fcd43a475f9f56a9b06555aa2c621136/.github/workflows/remove-wheels.yml#L19

again, focusing on "nightly".

**Comment by kou** [comment] 2025-02-24 21:41
Our nightly Windows wheel builds are broken recently. (They will be fixed by #45442.)

Is it related?

**Comment by raulcd** [comment] 2025-02-25 08:02
> I assume (don't have time to check) you're just seeing that we also keep only the last 5 uploads by default:

If I understand correctly that snippet on the GH actions if we upload a single wheel with a newer version, all wheels that have an older than 5 versions will be removed. That seems to match what we are seeing, we are still uploading newer wheels but the Windows wheels stopped to be uploaded 15 days ago due to CI failures.

> Our nightly Windows wheel builds are broken recently. (They will be fixed by https://github.com/apache/arrow/pull/45442.) Is it related?

Yes, it will be fixed today but it's more to understand when are those removed as this is the second time that something like this happens.

**Comment by matthewfeickert** [comment] 2025-02-26 07:05
> If I understand correctly that snippet on the GH actions if we upload a single wheel with a newer version, all wheels that have an older than 5 versions will be removed.

@raulcd Yes. Within 24 hours of an upload the CI will trim it down to 5 versions max (so you can have more than up there for a brief period).

I see that PR https://github.com/apache/arrow/pull/45442 has been merged now (👍). Let us know if in the next automated upload the Windows wheels aren't restored.
