### ISSUE TITLE
MSVCP140.dll in arrow distro out of date and caused a fault

### ISSUE THREAD

**Issue by andrewn3** [apache/arrow#44894] opened 2024-12-01 18:10 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

long story short, something I was doing caused a crash, I replaced the version in arrow python distro (MSVCP140.dll, version: **14.28.29334.0**) with (MSVCP140.dll, version: **14.40.33816.0**) and it worked.

Longer story, I was using Crewai in a virtualenv which crashed out with no useful information.  I found that Crewai's CSVSearchtool, uses chromadb, which would fail when using multiple batches with a csv file, I then discovered chroma uses Arrow and the root cause was the MSVCP140.dll provided in the arrow distro.  I upgraded to arrow dsitro18.1.0 but still the same so maybe something to address.  I renamed the msvcp140.dll file so it caused  the native OS version to be used which worked, so i copied it into the pyarrow directory and it works..   

Faulting application name: python3.12.exe, version: 3.12.7150.1013, time stamp: 0x66fb67fc
Faulting module name: MSVCP140.dll, version: **14.28.29334.0**, time stamp: 0x5fa9a827
Exception code: 0xc0000005
Fault offset: 0x0000000000012eb0
Faulting process id: 0x8C78
Faulting application start time: 0x1DB41E64EF6ECB0
Faulting application path: C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\python3.12.exe
Faulting module path: D:\Users\newla\crewai\financial_analyst1\financial_analyst\.venv\Lib\site-packages\pyarrow\MSVCP140.dll
Report Id: 781cf8e1-f816-4e82-b54a-7df070b535d1
Faulting package full name: PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0
Faulting package-relative application ID: Python

### Component(s)

Python

**Comment by QuLogic** [comment] 2024-12-02 03:26
See, e.g., https://github.com/matplotlib/matplotlib/pull/28687 if you can afford to do so.

**Comment by QuLogic** [comment] 2024-12-02 03:28
Also, this is a dupe of #44855.

**Comment by assignUser** [comment] 2024-12-02 04:14
Closing as duplicate, thanks for the report!

**Comment by QuLogic** [comment] 2024-12-02 04:32
I think you forgot to close...

**Closed** 2024-12-02 09:31 UTC
Labels: Type: bug, Component: Python
