### ISSUE TITLE
[Python] `pa.array` fails for values larger than the default type range when no type is specified

### ISSUE THREAD

**Issue by mariosasko** [apache/arrow#36520] opened 2023-07-06 23:08 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

E.g., I would expect the following to work:
```python
pa.array([2**64-1]) # OverflowError: Python int too large to convert to C long
```
But it doesn't unless `type=pa.uint64()` is specified. This is not aligned with NumPy/Pandas - both infer `dtype=np.uint64` for this array.

### Component(s)

Python

**Comment by jorisvandenbossche** [comment] 2023-07-13 13:22
Given the comments on the PR:

> Again, the problem is that the user will get different data types depending on the exact input values. This is fragile and error-prone.
If you know you need uint64, the solution is to ask explicitly for it.

I think we can close this issue as "won't fix" (and duplicate of https://github.com/apache/arrow/issues/19334)

**Closed by jorisvandenbossche** 2023-07-13 13:22 UTC
Labels: Type: bug, Component: Python
