### ISSUE TITLE
[Python] Missing docstring for `columns` parameter of `pyarrow.lib.Table.drop`

### ISSUE THREAD

**Issue by rtpsw** [apache/arrow#34041] opened 2023-02-04 07:28 UTC
### Describe the enhancement requested

The missing docstring causes CI failures. For example, [this CI job](https://github.com/apache/arrow/actions/runs/4087895935/jobs/7048956304):
```
pyarrow.lib.Table.drop
-> pyarrow.lib.Table.drop(self, columns)
PR01: Parameters {'columns'} not documented
```

### Component(s)

Python

**Comment by jorisvandenbossche** [comment] 2023-02-07 07:30
Duplicate of #34037

**Comment by Fokko** [comment] 2023-02-07 07:30
PR is ready in https://github.com/apache/arrow/pull/34038

**Closed by jorisvandenbossche** 2023-02-07 07:30 UTC
Labels: Type: enhancement, Component: Python
