### ISSUE TITLE
[CI][C#] Verification jobs for C# are currently failing

### ISSUE THREAD

**Issue by raulcd** [apache/arrow#43058] opened 2024-06-26 10:12 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

Tests are failing with several errors that seem to be related to (see the logs for more details):
```
 ----- Inner Stack Trace -----
   at Apache.Arrow.Tests.CDataSchemaPythonTest.PythonNet..ctor() in /Users/runner/work/crossbow/crossbow/arrow/csharp/test/Apache.Arrow.Tests/CDataInterfacePythonTests.cs:line 48
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  Failed Apache.Arrow.Tests.CDataSchemaPythonTest.ImportSchema [1 ms]
  Error Message:
   Class fixture type 'Apache.Arrow.Tests.CDataSchemaPythonTest+PythonNet' threw in its constructor
   ```
Job failures:
- [verify-rc-source-csharp-linux-almalinux-8-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9662756193/job/26653333060)
- [verify-rc-source-csharp-linux-conda-latest-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9662757091/job/26653338208)
- [verify-rc-source-csharp-linux-ubuntu-20.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9662755855/job/26653331783)
- [verify-rc-source-csharp-linux-ubuntu-22.04-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9662757625/job/26653340751)
- [verify-rc-source-csharp-macos-amd64](https://github.com/ursacomputing/crossbow/actions/runs/9662756794/job/26653335821)
- [verify-rc-source-csharp-macos-arm64](https://github.com/ursacomputing/crossbow/actions/runs/9662757771/job/26653341642)

The failures started when those commits were merged:
https://github.com/apache/arrow/compare/ff9921ffa89585be69ae85674bb365d03cb22ba4...f904928054fad89360d83015db5c23ac1ef86d05
There are several bump versions from dependabot on those that involves C#.

### Component(s)

C#, Continuous Integration

**Comment by raulcd** [comment] 2024-06-26 10:14
@CurtHagenlocher @adamreeve @eerhardt any idea what is happening? this is a blocker for 17.0.0

**Comment by CurtHagenlocher** [comment] 2024-06-26 12:20
The inner exception seems to be "Xunit.SkipException : PYTHONNET_PYDLL not set; skipping C Data Interface tests". This would happen if the environment variable PYTHONNET_PYDLL was not set on the VM image and is independent of any changes to product code. Something must have changed in the VM configurations?

**Comment by adamreeve** [comment] 2024-06-27 00:07
It looks like these tests are supposed to be skipped in the verification jobs: https://github.com/apache/arrow/blob/6680dcfbef4234782484cd8c2c3e0ce0cf9e9914/csharp/test/Apache.Arrow.Tests/CDataInterfacePythonTests.cs#L42

Maybe the `TEST_CSHARP` environment variable is no longer being set, or it's now set to something other than "1"?

**Comment by adamreeve** [comment] 2024-06-27 00:16
Actually the logs show that these are throwing an "Xunit.SkipException" so it seems like the check for `inVerificationJob` is correct, but the skip is being incorrectly treated as an error.

So I think this is probably due to the either #41842 or #41848

**Comment by adamreeve** [comment] 2024-06-27 00:30
I can reproduce this locally and the tests pass (are skipped properly) if I revert #41842

**Comment by adamreeve** [comment] 2024-06-27 00:51
I've created a bug for xunit: https://github.com/xunit/xunit/issues/2965

**Comment by CurtHagenlocher** [comment] 2024-06-27 01:55
I guess I don't have a firm grasp on the semantics of `TEST_CSHARP` or `GITHUB_ACTIONS`. These tests should certainly be run for at least some of the CI/checkin tests but perhaps not for all of them?

In any event, the xunit change is clearly a bug.

**Comment by raulcd** [comment] 2024-06-27 08:55
> I can reproduce this locally and the tests pass (are skipped properly) if I revert #41842

Should we revert this temporarily for the release and create a follow up issue to update once the downstream issue is fixed?

**Comment by adamreeve** [comment] 2024-06-28 01:54
> Should we revert this temporarily for the release and create a follow up issue to update once the downstream issue is fixed?

Yes I think that makes sense, I've made #43074 to revert the update and #43076 for the follow up.

**Comment by kou** [comment] 2024-06-28 02:50
Issue resolved by pull request 43074
https://github.com/apache/arrow/pull/43074

**Closed by kou** 2024-06-28 02:50 UTC
Labels: Type: bug, Component: C#, Component: Continuous Integration, Priority: Blocker
