### ISSUE TITLE
Failed building on LoongArch platform

### ISSUE THREAD

**Issue by liujiacheng777** [apache/arrow#34791] opened 2023-03-30 09:41 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

-- Configuring incomplete, errors occurred!
See also "/home/loongson/tmp/aa/arrow/cpp/build/CMakeFiles/CMakeOutput.log".

loongson@loongson-pc:~/tmp/arrow/cpp/build$ make
In file included from /home/loongson/tmp/aa/arrow/cpp/src/arrow/vendored/double-conversion/double-conversion.h:31,
                 from /home/loongson/tmp/aa/arrow/cpp/src/arrow/util/double_conversion.h:20,
                 from /home/loongson/tmp/aa/arrow/cpp/src/arrow/util/formatting.h:35,
                 from /home/loongson/tmp/aa/arrow/cpp/src/arrow/pretty_print.cc:41:
/home/loongson/tmp/aa/arrow/cpp/src/arrow/vendored/double-conversion/utils.h:118:2: error: #error Target architecture was not detected as supported by Double-Conversion.
 #error Target architecture was not detected as supported by Double-Conversion.
  ^~~~~
make[2]: *** [src/arrow/CMakeFiles/arrow_objlib.dir/build.make:466：src/arrow/CMakeFiles/arrow_objlib.dir/pretty_print.cc.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:684：src/arrow/CMakeFiles/arrow_objlib.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2

### Component(s)

C++

**Comment by assignUser** [comment] 2023-03-30 14:23
Duplicate of #34752

**Closed by assignUser** 2023-03-30 14:23 UTC
Labels: Type: bug, Component: C++
