### ISSUE TITLE
[Python] How to install pyarrow package in an anaconda virtual env running on rhel 8.6 on Linux on System z

### ISSUE THREAD

**Issue by fulwang** [apache/arrow#37697] opened 2023-09-13 16:29 UTC
### Describe the usage question you have. Please include as many useful details as  possible.

I need to install this pyarrow package inside an anaconda virtual env, what's the right steps to do?

while my first try gave me below error:
-------------------------------------------------------------------------------------------
CMake Error at CMakeLists.txt:261 (find_package):
        By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "Arrow", but
        CMake did not find one.

        Could not find a package configuration file provided by "Arrow" with any of
        the following names:

          ArrowConfig.cmake
          arrow-config.cmake

        Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
        "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
        provides a separate development package or SDK, be sure it has been
        installed.

      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-wqx2t8ot/pyarrow_b6e2b0832433457d846e9f2755b72c08/build/temp.linux-s390x-cpython-311/CMakeFiles/CMakeOutput.log".
      error: command '/usr/bin/cmake' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow

### Component(s)

Python

**Comment by kou** [comment] 2023-09-13 20:41
You need to build Apache Arrow C++ before you install pyarrow on the system because we don't provide pyarrow wheel for the system.

See https://arrow.apache.org/docs/dev/developers/python.html#building-on-linux-and-macos for details how to build Apache Arrow C++ and pyarrow.

**Comment by fulwang** [comment] 2023-09-14 07:00
Kou,

Many Thanks for the tips!

I just try to build Arrow C++ following the guide you mentioned, but when executing the step of creating anaconda virtual env, i encountered below issues. seems need to specify additional channels when issue this command?

I'm a newbie for python programming, could you kindly suggest what channels and how i can add them?
Thanks!

By the way, I'm build it on an redhat linux 8.6 (s390x) with python 3.11.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(base) [root@lpar50 ~]# 
(base) [root@lpar50 ~]# conda create -y -n pyarrow-dev -c conda-forge \
>        --file arrow/ci/conda_env_unix.txt \
>        --file arrow/ci/conda_env_cpp.txt \
>        --file arrow/ci/conda_env_python.txt \
>        --file arrow/ci/conda_env_gandiva.txt \
>        compilers \
>        python=3.11 \
>        pandas
Collecting package metadata (current_repodata.json): | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
\ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
/ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/linux-s390x/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/noarch/current_repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/linux-s390x/current_repodata.json HTTP/1.1" 200 None
| DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/linux-s390x/current_repodata.json HTTP/1.1" 200 None
done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): \ DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
/ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/noarch/repodata.json HTTP/1.1" 200 None
- DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/repodata.json HTTP/1.1" 304 0
\ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/linux-s390x/repodata.json HTTP/1.1" 304 0
| DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/linux-s390x/repodata.json HTTP/1.1" 200 None
/ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/linux-s390x/repodata.json HTTP/1.1" 200 None
done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - clang[version='>=11']
  - gflags
  - glog
  - benchmark[version='>=1.6.0']
  - rapidjson
  - google-cloud-cpp[version='>=1.34.0']
  - aws-sdk-cpp==1.11.68
  - compilers
  - flatbuffers

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-s390x
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-s390x
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-s390x
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(base) [root@lpar50 ~]#

**Comment by kou** [comment] 2023-09-14 07:08
@h-vetinari Could you help us as an conda expert?

**Comment by h-vetinari** [comment] 2023-09-14 07:25
The issue is unfortunately very simple: conda-forge has no builds at all for `linux-s390x`, see https://github.com/conda-forge/conda-forge.github.io/issues/1123.

Actually, we do have the GCC stack built for s390x, but it would take someone very dedicated (or better: several people) to roll out support to all packages, like was done for aarch64/ppc64le. The referenced issue describes the necessary next steps.

**Comment by fulwang** [comment] 2023-09-14 08:08
oops！That's really a bad news!
Anyway, many thanks for the help and clarification! @h-vetinari @kou

**Comment by kou** [comment] 2023-09-14 08:22
Oh, Thanks.
I close this.

**Closed by kou** 2023-09-14 08:22 UTC
Labels: Component: Python, Type: usage
