### ISSUE TITLE
[Java] Upgrade to JUnit 5 

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32996] opened 2022-09-18 23:32 UTC
**Reporter**: [Andréi Ósipov](https://issues.apache.org/jira/browse/ARROW-17768) / @andreoss
#### Subtasks:
- [ ] [[Java] Upgrade adapter/ to Junit 5](https://github.com/apache/arrow/issues/32997)
#### Related issues:
- [[Java] Upgrade to JUnit 5 ](https://github.com/apache/arrow/issues/21260) (supercedes)
- [[Java][FlightRPC] Upgrade to JUnit 5 ](https://github.com/apache/arrow/issues/32942) (supercedes)

<sub>**Note**: *This issue was originally created as [ARROW-17768](https://issues.apache.org/jira/browse/ARROW-17768). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by llama90** [comment] 2024-06-17 13:46
@lidavidm @vibhatha In my opinion, we can close this issue due to #41680.

**Comment by lidavidm** [comment] 2024-06-18 00:00
Duplicate of https://github.com/apache/arrow/issues/41680

**Closed by lidavidm** 2024-06-18 00:00 UTC
Labels: Type: enhancement, Component: Java
