### ISSUE TITLE
[Java] Upgrade adapter/ to Junit 5

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32997] opened 2022-09-18 23:34 UTC
**Reporter**: [Andréi Ósipov](https://issues.apache.org/jira/browse/ARROW-17769) / @andreoss
#### PRs and other links:
- [GitHub Pull Request #14164](https://github.com/apache/arrow/pull/14164)

<sub>**Note**: *This issue was originally created as [ARROW-17769](https://issues.apache.org/jira/browse/ARROW-17769). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by llama90** [comment] 2024-06-17 13:46
@lidavidm @vibhatha In my opinion, we can close this issue due to #41680.

**Comment by lidavidm** [comment] 2024-06-18 00:00
Duplicate of https://github.com/apache/arrow/issues/42030

**Closed by lidavidm** 2024-06-18 00:00 UTC
Labels: Component: Java, Type: task
