### ISSUE TITLE
[CI][Python] Failing builds due to an error when parsing timestamp in setuptools-scm

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#41563] opened 2024-05-07 04:22 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

Python builds started failing yesterday which is probably connected to the new release of setuptools-scm on 6 May (https://pypi.org/project/setuptools-scm/8.1.0/#history) with:

```python
...
    File "<string>", line 437, in parse_git
    File "/opt/conda/envs/arrow/lib/python3.9/site-packages/setuptools_scm/git.py", line 211, in parse
      return _git_parse_inner(
    File "/opt/conda/envs/arrow/lib/python3.9/site-packages/setuptools_scm/git.py", line 272, in _git_parse_inner
      node_date = wd.get_head_date() or datetime.now(timezone.utc).date()
    File "/opt/conda/envs/arrow/lib/python3.9/site-packages/setuptools_scm/git.py", line 131, in get_head_date
      return res.parse_success(
    File "/opt/conda/envs/arrow/lib/python3.9/site-packages/setuptools_scm/_run_cmd.py", line 77, in parse_success
      return parse(self.stdout)
    File "/opt/conda/envs/arrow/lib/python3.9/site-packages/setuptools_scm/git.py", line 121, in parse_timestamp
      return datetime.fromisoformat(timestamp_text).date()
  ValueError: Invalid isoformat string: '2024-05-06T14:29:03Z'
```

See:
https://github.com/apache/arrow/actions/runs/8970805528/job/24635130465?pr=40761#step:6:2896

### Component(s)

Continuous Integration, Python

**Comment by AlenkaF** [comment] 2024-05-07 04:23
cc @anjakefala @raulcd

**Comment by AlenkaF** [comment] 2024-05-07 07:31
Correction: the failing build is using `setuptools-scm` version `8.0.4`, same as other builds that have succeeded (https://github.com/apache/arrow/actions/runs/8971879323/job/24638601943). The new released version from yesterday was `8.1.0` so the new `setuptools-scm` release is not causing the failures.

Plus there has been similar failures couple of days ago:
- https://github.com/apache/arrow/actions/runs/8950932486/job/24586741006
- https://github.com/apache/arrow/actions/runs/8936352661/job/24546509659

**Comment by jorisvandenbossche** [comment] 2024-05-07 08:14
I don't understand why we _start_ to see those failures now, but the new setuptools_csm 8.1.0 might actually fix it: https://github.com/pypa/setuptools_scm/commit/49a89c9181f92c9e436b7b45a6388a536acac026

**Comment by jorisvandenbossche** [comment] 2024-05-07 08:14
Apparently it was caused by the latest version of git: https://github.com/pypa/setuptools_scm/issues/1038

**Comment by AlenkaF** [comment] 2024-05-07 08:30
The version of `setuptools_scm` on conda-forge is still `8.0.4`. I guess restricting supported git versions with python 3.9 doesn't work for us?

**Comment by jorisvandenbossche** [comment] 2024-05-07 08:34
It might be faster to try to get an updated version on conda-forge (I triggered https://github.com/conda-forge/setuptools_scm-feedstock/pull/73)

**Comment by jorisvandenbossche** [comment] 2024-05-08 07:50
This is working again on the latest PR builds I am seeing, so closing

**Closed by jorisvandenbossche** 2024-05-08 07:50 UTC
Labels: Component: Python, Component: Continuous Integration
