### ISSUE TITLE
[CI]: Nightly csharp verification test fails on mac / arm

### ISSUE THREAD

**Issue by westonpace** [apache/arrow#15234] opened 2023-01-07 01:12 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

This runner is a self hosted runner and the port 5001 is in use already.

### Component(s)

C#

**Comment by assignUser** [comment] 2023-01-07 01:18
Duplicate of https://issues.apache.org/jira/browse/ARROW-16795

**Closed by assignUser** 2023-01-07 01:18 UTC
Labels: Type: bug, Component: C#, Component: Continuous Integration
