### ISSUE TITLE
[Python] Substrait integration tests fail wit Invalid NamedTable Source

### ISSUE THREAD

**Issue by wjones127** [apache/arrow#35012] opened 2023-04-10 17:25 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

From crossbow job test-conda-python-3.9-substrait

https://github.com/ursacomputing/crossbow/actions/runs/4653274342/jobs/8234006878

Also produces:

```
TypeError: <lambda>() takes 1 positional argument but 2 were given
```

### Component(s)

Python

**Comment by wjones127** [comment] 2023-04-10 17:26
cc @vibhatha

**Comment by vibhatha** [comment] 2023-04-11 02:59
@wjones127 this is a failure in the Substrait Integration tests. I will look into the details and see what needs to be fixed.

**Comment by vibhatha** [comment] 2023-04-11 03:21
@wjones127 the issue is in the Consumer testing API, the `NamedTableProvider` definition has been changed by this [PR](https://github.com/apache/arrow/pull/34279)

Specifically it shows how the Python lambda needs to be changed in [here](https://github.com/apache/arrow/pull/34279/files#diff-45b2fdb2f4dc485af1c4ff5f458c9037af718f604112d37055f9734a23186ba6), so doing the same in the consumer testing API would be sufficient. 

cc @westonpace I created an issue [here](https://github.com/substrait-io/consumer-testing/issues/18)

**Comment by vibhatha** [comment] 2023-04-11 16:35
@wjones127 the PR is ready here: https://github.com/substrait-io/consumer-testing/pull/19

Let's see how it goes.

**Comment by westonpace** [comment] 2023-04-14 22:23
@github-actions crossbow submit test-conda-python-3.9-substrait

**Comment by westonpace** [comment] 2023-04-14 22:45
Ah...this is an issue...not a PR.  :facepalm: 

On the bright side, it seems the nightly test is passing again: https://github.com/ursacomputing/crossbow/tree/nightly-tests-2023-04-14-0-github-test-conda-python-3.9-substrait

So I think we can close this.

**Closed** 2023-04-15 00:30 UTC
Labels: Type: bug, Component: Python

**Comment by vibhatha** [comment] 2023-04-15 01:17
@westonpace this was resolved by fixing the NamedTableProvider definition in consumer-testing repo.
