### ISSUE TITLE
[Python] Remove deprecated `use_async`

### ISSUE THREAD

**Issue by Fokko** [apache/arrow#34033] opened 2023-02-03 16:45 UTC
### Describe the enhancement requested

Has been deprecated since Arrow 7.0.0, time to make things nice and clean: https://issues.apache.org/jira/browse/ARROW-13554

### Component(s)

Python

**Comment by jorisvandenbossche** [comment] 2023-02-07 15:45
Duplicate of #30774

**Closed by jorisvandenbossche** 2023-02-07 15:45 UTC
Labels: Type: enhancement, Component: Python
