### ISSUE TITLE
[CI][Swift] Recent change to build options causing build errors when Arrow included as dependancy

### ISSUE THREAD

**Issue by lukedg97** [apache/arrow#42212] opened 2024-06-20 00:31 UTC
Reposting comment as new Issue as original issue was closed:

hello, I think I might be running into an issue related to this change. 

I am seeing the error `Conflicting options '-warnings-as-errors' and '-suppress-warnings'` on some of my builds. I have not been able to find a fix yet for those machines that have seen this. The best I have been able to find on this issue is this forum post: https://forums.swift.org/t/warnings-as-errors-in-sub-packages/70810 which seems to imply that this is an anti-pattern for swift packages to include the option '-warnings-as-errors'. It seems that when included in a project as a dependency swift automatically adds '-suppress-warnings' to that package on build which then conflicts with the other option and causes the build to fail.

I will update with any additional findings or a fix from the user side if I can find it.

_Originally posted by @lukedg97 in https://github.com/apache/arrow/issues/42087#issuecomment-2179608793_

**Comment by lukedg97** [comment] 2024-06-20 00:34
seeing this post: https://forums.swift.org/t/warnings-as-errors-for-libraries-frameworks/58393

it may be possible to include the flag as an option in the CI without including it in the manifest. I'm not familiar enough with the setup to say for sure though.

**Comment by assignUser** [comment] 2024-06-20 00:46
> to include the flag as an option in the CI without including it in the manifest

This sounds like the way to go, at least coming from C++ it is always extra annoying when projects set `-Werror` (which has the same effect) by default causing my build to fail for reasons not within my code...

**Comment by assignUser** [comment] 2024-06-20 01:39
Closing as duplicate of #42213 (because there is a PR open already even if this issue was first :) )

**Closed by assignUser** 2024-06-20 01:39 UTC

**Comment by abandy** [comment] 2024-06-20 02:04
Thanks @lukedg97 for making this issue!  I didn't see this before opening the other issue.
