### ISSUE TITLE
feather read a part of columns slower than read the entire file

### ISSUE THREAD

**Issue by JiaRu2016** [apache/arrow#10138] opened 2021-04-23 05:16 UTC
I'v found that read several columns of a feather DataFrame is slower than read the entire file. The pattern is 
- read half of the columns consumes roughly same time as read entire file
- read more than 50% of columns cost more time than reading entire file
- only reading less than 50% of columns DO saves time

Is it a bug or expected behavior ?

Timming code is like this, I could write reproducing script if need.

```python
t0 = time.perf_counter()
df = feather.read_dataframe(path, columns=cols)  # read some columns
t1 = time.perf_counter()
elapsed = t1 - t0

t0 = time.perf_counter()
df = feather.read_dataframe(path)    # read entire file
t1 = time.perf_counter()
elapsed = t1 - t0
```

**Comment by jorisvandenbossche** [comment] 2021-04-26 18:49
A small reproducing script would be welcome!

**Comment by JiaRu2016** [comment] 2021-04-27 06:22
here is a reproducing script and output. Here the output indicates that reading 50% of the columns or more do not save any time, so speed measurement (GB/s) decrease as number of columns to read decrease. 

In theory, what will affect reading speed? The only factor I could thought of is continuity of columns, ie. maybe reading columns [1 2 3 4 ... 10] faster than random picked 10 columns like [42, 24, 15, 9 ...]? Any document related to on-disk-storage of feather format?


reproducing scritpt:
```python
import numpy as np
import pandas as pd
import os
import time
import tqdm


n, m = 10_0000, 135
dtype = np.float64  # 100_0000 * 135 * 8bytes = 1.005 GB per file
nbytes_per_file = n * m * np.finfo(dtype).bits / 8
nfiles = 10

#output_dir = '/dev/shm/io_speed_test_feather_cols/'        # /dev/shm
output_dir = '/auto/rjia/io_speed_test_feather_cols/'      # local disk
#output_dir = '/cpfs/user/rjia/io_speed_test_feather_cols/'  # network file system


def setup():
    import shutil
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
        print(f'rm existing dir: {output_dir}')
    os.makedirs(output_dir)
    print(f'hostname: {os.uname()[1]}')
    print(f'# files = {nfiles}, bytes per file = {nbytes_per_file / 1024**2} MB')


def generate_files():
    for i in tqdm.tqdm(range(nfiles), desc='generate_files'):
        arr = np.random.normal(size=(n, m)).astype(dtype)
        df = pd.DataFrame(arr, columns=[f'x{j}' for j in range(m)])
        df.to_feather(f'{output_dir}/{i}.feather')


def summary(tag, seconds_list, nbytes_per_file):
    speed_GBs = [nbytes_per_file / 1024**3 / seconds for seconds in seconds_list]
    mean = np.mean(speed_GBs)
    std = np.std(speed_GBs)
    n = len(seconds_list)
    print(f'[ {tag} ] speed (GB/s): mean = {mean}, std = {std}, n = {n}; total time_elapse: {sum(seconds_list)}')


def main():
    for cols in [1.0, 0.8, 0.6, 0.4, 0.2]:
        generate_files()  # genreate new files each time run, to avoid cache
        
        if cols == 1.0:
            columns = None
        else:
            columns = sorted(np.random.choice(m, size=int(cols*m), replace=False).tolist())
            #print(f'columns len: {columns.__len__()}')

        elapse_lst = []
        for i in tqdm.tqdm(range(nfiles), desc=f'read_{cols}'):
            t0 = time.perf_counter()
            df = pd.read_feather(f'{output_dir}/{i}.feather', columns=columns)
            t1 = time.perf_counter()
            elapse = t1 - t0
            elapse_lst.append(elapse)
        summary(f'read_{cols}', elapse_lst, nbytes_per_file * cols)
    

if __name__ == "__main__":
    setup()
    main()
```

otuput (filter out progress bars)
```
# # files = 10, bytes per file = 102.996826171875 MB
# [ read_1.0 ] speed (GB/s): mean = 1.0219851767027053, std = 0.03415322016211257, n = 10; total time_elapse: 0.9852561568841338
# [ read_0.8 ] speed (GB/s): mean = 0.7865783976845142, std = 0.07702083870020748, n = 10; total time_elapse: 1.0330937625840306
# [ read_0.6 ] speed (GB/s): mean = 0.5654617667430214, std = 0.03666601160766624, n = 10; total time_elapse: 1.071873253211379
# [ read_0.4 ] speed (GB/s): mean = 0.46550180257149, std = 0.05855073295937812, n = 10; total time_elapse: 0.8783506583422422
# [ read_0.2 ] speed (GB/s): mean = 0.27125950048361597, std = 0.023256912005982042, n = 10; total time_elapse: 0.7473218226805329
```

**Comment by westonpace** [comment] 2021-04-27 22:44
> Any document related to on-disk-storage of feather format?

The feather format is more generally referred to now as the "Arrow IPC File Format" (not to be confused with Arrow IPC Streaming Format) and is documented [here](https://arrow.apache.org/docs/format/Columnar.html#ipc-file-format).

> I've found that read several columns of a feather DataFrame is slower than read the entire file

Currently, if you only select some columns, the Arrow IPC reader will still read in the entire table from disk.  The feather/IPC format does not currently implement partial-record-batch reads of any kind.

Out of curiosity which OS are you running?

When I run your reproduction script I do see results similar to what you have posted.  However, I believe this is due to issues with the reproduction script.  Generating new files each time will not emulate a clean cache.  Instead, when you go to your benchmark's read phase, you will have a bunch of dirty OS pages in the cache (but they will be in the cache and the OS will serve them from the cache).

Just to reinforce this, you are getting read speeds of 1GB/s (which includes decoding time).  Unless you have a very fast SSD that seems unlikely.

If you are intending a hot-cache test then you should put `os.sync` after each of the writes (or, more easily, just write the files once in setup).  If you are intending a cold-cache test then you should put `os.sync` AND something like...
```
        # with open('/proc/sys/vm/drop_caches', 'w') as f:
        #     f.write("1\n")
```
...after each write.  When I run a hot-cache test I see consistently faster times the fewer columns I am loading.  When I run a cold-cache test I see so much noise from the actual disk I/O that it is very hard to see the benefit of column selection (although I presume it is still there).

**Comment by westonpace** [comment] 2021-04-28 18:56
Actually, you do see some benefit in the cold-cache case if you are using memory-mapped I/O (the default).  Arrow is still mapping the entire file but it only accesses the parts it needs:

```
[ read_1.0 ] speed (GB/s): mean = 0.10454136550934692, std = 0.007475733527851558, n = 10; total time_elapse: 9.674335052999595
[ read_0.8 ] speed (GB/s): mean = 0.08324025202688382, std = 0.007408401336626204, n = 10; total time_elapse: 9.73901134300013
[ read_0.6 ] speed (GB/s): mean = 0.06967461380067123, std = 0.005036855302449362, n = 10; total time_elapse: 8.70547049200104
[ read_0.4 ] speed (GB/s): mean = 0.06235823834380603, std = 0.006652843286404212, n = 10; total time_elapse: 6.526506393001
[ read_0.2 ] speed (GB/s): mean = 0.05067126099456597, std = 0.004539982065432586, n = 10; total time_elapse: 4.0006215649991645
```

My guess is that it is not linear because you take an HDD penalty moving from sequential scan to random access.

**Comment by westonpace** [comment] 2021-04-28 19:00
Indeed, the speedup is more linear on an SSD...
```
[ read_1.0 ] speed (GB/s): mean = 0.3630993232511599, std = 0.05952451935546521, n = 10; total time_elapse: 2.9084372880015508
[ read_0.8 ] speed (GB/s): mean = 0.36376093584884195, std = 0.008990062151343865, n = 10; total time_elapse: 2.213474280999435
[ read_0.6 ] speed (GB/s): mean = 0.35984781969486807, std = 0.004778046558776139, n = 10; total time_elapse: 1.6773865380018833
[ read_0.4 ] speed (GB/s): mean = 0.3290578456574669, std = 0.07105464075317411, n = 10; total time_elapse: 1.3731986839993624
[ read_0.2 ] speed (GB/s): mean = 0.2799392331920786, std = 0.07746319562812805, n = 10; total time_elapse: 0.8508833189998768
```

**Comment by JiaRu2016** [comment] 2021-05-10 09:25
the result I post was run on a Linux server whose disk is HDD. I also run on my Mac whose disk is SSD, then the result is same as @westonpace 's result.

so I agree with his guess:

> 
> My guess is that it is not linear because you take an HDD penalty moving from sequential scan to random access.

**Comment by wesm** [comment] 2021-05-28 15:58
I think this can be mitigated by disabling memory mapping. But in general these code paths have not been especially optimized for high random access latency

**Closed** 2021-06-09 14:06 UTC
