### ISSUE TITLE
【C++】how to use jemalloc as default memory pool

### ISSUE THREAD

**Issue by deep826** [apache/arrow#38651] opened 2023-11-09 15:23 UTC
### Describe the usage question you have. Please include as many useful details as  possible.

I installed the arrow library following the way recommended in official docs.
arrow version: 13.0.0
ubuntu version: 20.04
ARROW_JEMALLOC: ON
I want to use jemalloc as default memory allocator, so i wrote the code as following:
`auto s = arrow::jemalloc_memory_pool(&mem_pool_);`
and then get the error message:  "msg:NotImplemented: This Arrow build does not enable jemalloc".
Is there something wrong? what's the default memory allocator if i write `mem_pool_ = arrow::default_memory_pool();` ?
ps: I also set the env variable 'ARROW_DEFAULT_MEMORY_POOL' to 'jemalloc'

### Component(s)

C++

**Comment by kou** [comment] 2023-11-09 20:36
Could you show your full Apache Arrow C++ build log?

**Comment by 520fengling** [comment] 2023-11-10 03:16
> Could you show your full Apache Arrow C++ build log?

I didn't build Arrow C++ by myself. I installed Arrow C++ following the way in official docs.
here: https://arrow.apache.org/install/#:~:text=C%2B%2B%20and%20GLib%20(C)%20Packages%20for%20Debian%20GNU/Linux%2C%20Ubuntu%2C%20AlmaLinux%2C%20CentOS%20and%20Amazon%20Linux

**Comment by kou** [comment] 2023-11-13 01:02
Hmm. I couldn't reproduce this.

```cpp
#include <arrow/memory_pool.h>
#include <iostream>

int
main(void)
{
  std::cout << arrow::default_memory_pool()->backend_name() << std::endl;
  return 0;
}
```

```console
$ g++ -std=c++17 a.cpp $(pkg-config --cflags --libs arrow)
$ ./a.out
jemalloc
```

**Comment by deep826** [comment] 2023-11-13 07:25
> ```c++
> arrow::default_memory_pool()
> ```
thks!
I found where the problem is. The container I used pre-installed arrow & parquet library, and I install them again. I used cmake `find_package` command to find the libararies (actually pre-installed version: 10.1.0). 
After linking the libraries which versions are 13.0.0, the problem solved, default memory_pool is jemalloc.

**Comment by kou** [comment] 2023-11-13 07:32
That's good to hear.
I close this.

**Closed by kou** 2023-11-13 07:32 UTC
Labels: Component: C++, Type: usage
