### ISSUE TITLE
[Python][Flight] Expose FlightInfo & FlightEndpoint attributes to python

### ISSUE THREAD

**Issue by janosik47** [apache/arrow#42095] opened 2024-06-11 07:42 UTC
### Describe the enhancement requested

Both `FlightInfo` and `FilghtEndpoint` C++ classes contains attributes which are not exposed to pyarrow

`FlightEndpoint`:
 * `std::optional<Timestamp> expiration_time;`
 * `std::string app_metadata;`

`FlightInfo`:
 * `bool ordered;`
 * `std::string app_metadata;`

### Component(s)

FlightRPC, Python

**Comment by lidavidm** [comment] 2024-06-11 07:46
Duplicate of #36954 I believe

**Comment by lidavidm** [comment] 2024-06-11 07:54
Can we add it to that ticket?

**Comment by janosik47** [comment] 2024-06-11 07:57
I guess so, I am fine with adding metadata into the other ticket and close this one as duplicate

**Comment by lidavidm** [comment] 2024-06-11 08:05
Updated the other ticket

Duplicate of https://github.com/apache/arrow/issues/36954

**Closed by lidavidm** 2024-06-11 08:05 UTC
Labels: Type: enhancement, Component: Python, Component: FlightRPC
