### ISSUE TITLE
Python 3.10 wheel

### ISSUE THREAD

**Issue by kukushking** [apache/arrow#11622] opened 2021-11-05 10:51 UTC
Hi arrow team, can we expect 3.10 wheel any time soon? pyarrow is a major dependency of our project and we'd like to [support 3.10](https://github.com/awslabs/aws-data-wrangler/issues/973) as soon as possible. Thanks!

**Comment by ianmcook** [comment] 2021-11-05 14:31
@kukushking Python 3.10 wheels are available for the latest release of Arrow: https://pypi.org/project/pyarrow/6.0.0/#files

**Comment by kukushking** [comment] 2021-11-05 17:33
Just FYI - project info on PyPI doesn't look correct then

**Comment by ianmcook** [comment] 2021-11-06 01:08
@kukushking could you please describe the problem you are experiencing so we can try to reproduce it and diagnose the cause? Thanks

**Comment by ianmcook** [comment] 2021-11-06 19:41
Oh, I see now that Python 3.10 is not included on this list on PyPI. @kszucs can we fix that?
![5EEF41C3-F7F3-4514-BBBA-8952028AF643](https://user-images.githubusercontent.com/280509/140621853-7d22ff31-be2a-4c95-ab26-05033d629158.jpeg)

**Comment by kszucs** [comment] 2021-11-08 22:15
Should be fixed in the upcoming wheels by https://github.com/apache/arrow/commit/bda4a2fe9cccfd719859ea5054068cfeadc1dc20

**Closed** 2021-11-10 09:25 UTC
