### ISSUE TITLE
[Python] Expose decryption properties in ParquetFragmentScanOptions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31410] opened 2022-03-21 17:01 UTC
Parquet modular encryption is now available in the Python Parquet APIs. However, it's not available through datasets, as `ParquetFragmentScanOptions` currently doesn't expose the `FileDecryptionProperties` (it does in C++).

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-15986) / @pitrou
#### Related issues:
- [[C++][Dataset][Parquet] Support parquet modular encryption in the new Dataset API](https://github.com/apache/arrow/issues/29238) (depends upon)

<sub>**Note**: *This issue was originally created as [ARROW-15986](https://issues.apache.org/jira/browse/ARROW-15986). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment] 2023-08-15 08:33
Closing as duplicate of #29238 (the [ARROW-13593](https://issues.apache.org/jira/browse/ARROW-13593) mentioned above)

**Closed** 2023-08-15 08:34 UTC
Labels: Type: enhancement, Component: Parquet, Component: Python
