### ISSUE TITLE
[Python] Parquet file writes incorrect booleans on large file with default write batch size

### ISSUE THREAD

**Issue by droher** [apache/arrow#33605] opened 2023-01-11 04:50 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

I found a case in which Pyarrow writes a Parquet file with incorrect boolean values.

Using this CSV (9 million rows): https://pub-4550af7adec143a391557444b6e41067.r2.dev/event_baserunning_advance_attempt.csv.gz

I can find at least a handful of boolean values that flip incorrectly when writing to Parquet, but not CSV.
```
from pyarrow import csv, parquet

table = csv.read_csv(
        "event_baserunning_advance_attempt.csv",
        convert_options=csv.ConvertOptions(
            strings_can_be_null=True,
        )
    )
  parquet.write_table(table, "test.parquet")
  csv.write_csv(table, "test.csv")
```
For a specific example, line 8432295 in the original file reads:
`ANA201405230,50,1,First,Second,true,false,false,false,false`
The new CSV file translates it correctly:
`"ANA201405230",50,1,"First","Second",true,false,false,false,false`
But the Parquet file flips the first boolean value:
`ANA201405230,50,1,First,Second,false,false,false,false,false`

 It looks like the issue can be resolved with a much larger `write_batch_size` than the default setting:
```
parquet.write_table(table, "test.parquet", write_batch_size=1000000)
```
~The above change will output the correct row.~ EDIT: There are still incorrect rows; but batch size changes which rows have values flipped.

The error appears to be deterministic, as the rows I've spot-checked are wrong each time, even with a variety of changes to settings and environments.
This specific row is incorrect each time in each of the following environments/settings:
- Pyarrow Versions: 8.0.0, 10.0.1
- OS: 2020 Macbook M1 on MacOS 13.1, Ubuntu 22.04
- Other `write_table` options tried: version, data_page_version, flavor, use_dictionary, compression

### Component(s)

Parquet, Python

**Comment by wjones127** [comment] 2023-01-11 18:05
Hi @droher. I was unable to reproduce this with PyArrow 10.0.1. The data read back from Parquet always is equal to the data originally read from the CSV file.

Below is what I tried. Could you clarify how you checked the values in the Parquet file?

```python
In [1]: from pyarrow import csv, parquet
   ...: import pyarrow.dataset as ds

In [2]: table = csv.read_csv(
   ...:     "~/Downloads/event_baserunning_advance_attempt.csv.gz",
   ...:     convert_options=csv.ConvertOptions(
   ...:         strings_can_be_null=True,
   ...:     )
   ...: )
   ...: table.validate(full=True)

In [3]: parquet.write_table(table, "test.parquet")
   ...: table_pq = parquet.read_table("test.parquet")
   ...: table_pq.validate(full=True)

In [4]: table.equals(table_pq)
Out[4]: True

In [5]: table.filter((ds.field("game_id") == "ANA201405230") & (ds.field("event_id") == 50)).to_pandas()
Out[5]:
        game_id  event_id  sequence_id baserunner attempted_advance_to  is_successful  advanced_on_error_flag  safe_on_error_flag  rbi_flag  team_unearned_flag
0  ANA201405230        50            1      First               Second           True                   False               False     False               False

In [6]: table_pq.filter((ds.field("game_id") == "ANA201405230") & (ds.field("event_id") == 50)).to_pandas()
Out[6]:
        game_id  event_id  sequence_id baserunner attempted_advance_to  is_successful  advanced_on_error_flag  safe_on_error_flag  rbi_flag  team_unearned_flag
0  ANA201405230        50            1      First               Second           True                   False               False     False               False

In [7]: parquet.write_table(table, "test.parquet", write_batch_size=10000)
   ...: table_pq = parquet.read_table("test.parquet")
   ...: table_pq.validate(full=True)

In [8]: table.equals(table_pq)
Out[8]: True
```

**Comment by droher** [comment] 2023-01-11 18:32
I checked the values by querying them directly in duckdb 0.6.1 and using [Tad](https://github.com/antonycourtney/tad). Both yielded the incorrect result.

In duckdb the query was
```
SELECT * FROM 'test.parquet'
WHERE game_id = 'ANA201405230'
   AND event_id = 50
```

However, when I use your code, I also get the correct result. I also get the correct result when reading from Pandas (tested it on both the pyarrow or fastparquet engine).

It looks like Tad uses duckdb internally as well, so it looks like this could be a duckdb read issue instead of an arrow write issue.

**Comment by droher** [comment] 2023-01-11 18:40
I checked duckdb's source code, and while they generally have a pretty tight integration with Arrow, it looks like they don't rely on Arrow for reading Parquet files: https://github.com/duckdb/duckdb/blob/master/extension/parquet/column_reader.cpp

So it seems likely that this issue is on duckdb's end - I will follow up with them.

**Comment by droher** [comment] 2023-01-18 17:43
@wjones127 I'm not sure whether I should close this or leave that to the maintainers, but from my end it looks like there's no action needed on Arrow's end - this was pretty conclusively on the DuckDB side and they have resolved it.

**Comment by wjones127** [comment] 2023-01-18 17:46
We can close it 👍

**Closed by wjones127** 2023-01-18 17:46 UTC
Labels: Type: bug, Component: Parquet, Component: Python, Priority: Critical
