### ISSUE TITLE
[R] expose AsofJoinNode

### ISSUE THREAD

**Issue by rdavis120** [apache/arrow#35552] opened 2023-05-11 15:01 UTC
### Describe the enhancement requested

Expose the C++ AsofJoinNode to the R arrow package.  This would be similar to what was done in python:  https://github.com/apache/arrow/issues/34235

In dplyr, it would map to left_join(x, y, by=join_by(closest(...))

### Component(s)

R

**Comment by nealrichardson** [comment] 2023-05-12 12:50
Duplicate of #20383?

**Closed** 2023-05-12 14:47 UTC
Labels: Type: enhancement, Component: R
