### ISSUE TITLE
[R] table_to_parquet factor handling

### ISSUE THREAD

**Issue by pomatim** [apache/arrow#44509] opened 2024-10-23 10:46 UTC
### Describe the enhancement requested

Hi,
Excellent package! I've just noticed that when using parquetize::table_to_parquet factors are not transformed into strings, but instead they're turned into numeric vectors (using the underlying factor coding). So for example if you have a labelled factor in Stata and you turn it into a parquet file using table_to_parquet, you lose the underlying value labels. Obviously one could load the Stata file into R and then turn it into parquet (and or change all factors to strings in R), but that means loading the original file into R memory first. If table_to_parquet could automatically turn all factors into strings it would save a huge amount of time...Thank you!

### Component(s)

R

**Comment by eitsupi** [comment] 2024-10-26 03:28
Here is the `arrow` package's issue tracker, are you sure the issue is with the arrow package?
If so, a reproducible example could be posted to help solve the problem.

If you are looking for an issue tracker for the `parquetize` package, I think it is <https://github.com/ddotta/parquetize>

**Comment by thisisnic** [comment] 2024-11-11 17:17
I'm gonna close this as it looks like it's not an arrow-specific issue, but relates to parquetize, but feel free to reopen if I'm incorrect

**Closed by thisisnic** 2024-11-11 17:17 UTC
Labels: Type: enhancement, Component: R
