### ISSUE TITLE
[Python]: pyarrow.compute.mean overflowing when numeric sum exceeds int64 max

### ISSUE THREAD

**Issue by mroeschke** [apache/arrow#34913] opened 2023-04-05 21:53 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

```
In [15]: import numpy as np; import pyarrow as pa

In [16]: pa.compute.mean(pa.array([np.iinfo(np.int64).max, 1]))
Out[16]: <pyarrow.DoubleScalar: -4.611686018427388e+18>

In [17]: pa.__version__
Out[17]: '11.0.0'
```

Haven't checked, but I suspect if mean is calculated as `sum(values) / len(values)`, `sum(values)` might be overflowing before performing the divisor.

### Component(s)

Python

**Comment by assignUser** [comment] 2023-04-05 21:55
Thanks for the very clear reprex! 

I am going to close this though as it is a duplicate of #34909

**Comment by mroeschke** [comment] 2023-04-05 21:57
Thanks! Sorry for not searching the issue tracker first

**Closed** 2023-04-05 21:56 UTC
Labels: Type: bug, Component: Python
