### ISSUE TITLE
How to read data from multiple locations while using Flight SQL JDBC driver

### ISSUE THREAD

**Issue by Srivatzn** [apache/arrow#35829] opened 2023-05-30 19:45 UTC
### Describe the usage question you have. Please include as many useful details as  possible.

Hello folks, 

I am connecting to my flight server using Arrow Flight JDBC driver(12.0.0). As per the [sequence diagram](https://arrow.apache.org/docs/format/FlightSql.html) for executing a prepared statement, the DoGET method is invoked for each endpoint in the FlightInfo. However, I am unable to get this working if I provide multiple locations in the FlightInfo response. The client iterates on the endpoints but always connects to the host & port configured as part of the JDBC connect string and does not switch to the location(s) passed in the FlightInfo.

JDBC URL: 

> jdbc:arrow-flight-sql://primaryendpoint:50051

Below is a sample FlightInfo object. For this, I expect the client to connect to `secondaryendpoint:50051` for streaming data but the DoGet calls are executed on the `primaryendpoint:50051` location which is part of the initial JDBC connect string.

> [<pyarrow.flight.FlightEndpoint ticket=<pyarrow.flight.Ticket ticket=b'GET-DATA'> locations=[<pyarrow.flight.Location b'grpc+tcp://secondaryendpoint:50051'>]>]

Any insights on this behavior and how can I get the client to switch to the locations for the DoGet operation? Is my understanding of the FlightRPC patterns correct?

### Component(s)

FlightRPC, Java

**Comment by lidavidm** [comment] 2023-05-30 19:56
This is not currently implemented in the JDBC driver, correct :/ contributions would be welcome. (I think there was an earlier issue about it, too.)

**Comment by lidavidm** [comment] 2023-05-30 19:58
Duplicate of https://github.com/apache/arrow/issues/34532.

There's a partial PR listed in that issue - if you're interested in taking it across the finish line I'd be happy to review and/or answer any questions.

**Closed by lidavidm** 2023-05-30 19:58 UTC
Labels: Component: Java, Component: FlightRPC, Type: usage
