### ISSUE TITLE
[Java] CycloneDX Unable to load the mojo 'makeBom'

### ISSUE THREAD

**Issue by davisusanibar** [apache/arrow#36371] opened 2023-06-29 05:14 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

There are random scenarios where cyclonedx-maven-plugin:2.7.6:makeBom finished with errors like this:

````
 Failed to execute goal org.cyclonedx:cyclonedx-maven-plugin:2.7.6:makeBom (default) on project arrow-memory-netty: Execution default of goal org.cyclonedx:cyclonedx-maven-plugin:2.7.6:makeBom failed: Unable to load the mojo 'makeBom' (or one of its required components) from the plugin 'org.cyclonedx:cyclonedx-maven-plugin:2.7.6': com.google.inject.ProvisionException: Unable to provision, see the following errors:
````

Errors Java Jobs:
- Arrow Memory - Netty: https://github.com/apache/arrow/actions/runs/5340264004/jobs/9679885230
- Arrow Flight SQL JDBC Driver Core: https://github.com/apache/arrow/actions/runs/5366232872/jobs/9735552069

There is a workaround that involves running the job twice, and in some cases the problem does not occur.

### Component(s)

Java

**Comment by lidavidm** [comment] 2023-07-05 13:42
Still happening, e.g. https://github.com/apache/arrow/actions/runs/5456482821/jobs/9947337600?pr=36351

**Comment by danepitkin** [comment] 2023-08-11 18:42
More proof: https://github.com/apache/arrow/actions/runs/5826063750/job/15799151443

So far I've seen it on both JDK 17 and 18 now.

**Comment by danepitkin** [comment] 2023-08-14 18:50
PR https://github.com/apache/arrow/pull/37125 just bumped the maven version for JDK 17/20 from 3.8.5 -> 3.9.3. Let's see if we continue to see this issue with the newer maven version.

**Comment by danepitkin** [comment] 2023-09-20 18:08
I've been browsing Java failures[1] and haven't seen this issue reproduced since upgrading maven over a month ago. I'm going to close this PR and assume it is resolved. Feel free to reopen if the issue reappears!

[1]https://github.com/apache/arrow/actions/workflows/java.yml?query=is%3Afailure

**Closed by danepitkin** 2023-09-20 18:08 UTC
Labels: Type: bug, Component: Java
