### ISSUE TITLE
[Go] [arrow/ipc/writer] voffsets are not updated when Binary-like arrays get truncated

### ISSUE THREAD

**Issue by notfilippo** [apache/arrow#41993] opened 2024-06-05 21:38 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

I've stumbled upon this bug while playing around with the results returned from [datafusion](https://github.com/apache/datafusion). It seems that in certain scenarios multiple arrays from different record batches, representing the same column, might share their value buffer.  The problem arises when trying to write those records using an `ipc.Writer`: If one of the columns which has a single shared buffer happens to be of a binary type the written value is invalid. 

This happens because each array's value buffer [gets truncated to only the part referred to by its offsets](https://github.com/apache/arrow/blob/9ee6ea701e20d1b47934f977d87811624061d597/go/arrow/ipc/writer.go#L592) but the offsets are never updated, so now they potentially point to memory outside of the truncated values. When trying to read the binary-like array via the `ipc.Reader` an error gets returned: `string offsets out of bounds of data buffer`.

How to reproduce:

```go
func main() {
	var buf bytes.Buffer
	buf.WriteString("apple")
	buf.WriteString("pear")
	buf.WriteString("banana")
	values := buf.Bytes()

	offsets := []int32{5, 9, 15} // <-- only "pear" and "banana"
	voffsets := arrow.Int32Traits.CastToBytes(offsets)

	validity := []byte{0}
	bitutil.SetBit(validity, 0)
	bitutil.SetBit(validity, 1)

	data := array.NewData(
		arrow.BinaryTypes.String,
		2, // <-- only "pear" and "banana"
		[]*memory.Buffer{
			memory.NewBufferBytes(validity),
			memory.NewBufferBytes(voffsets),
			memory.NewBufferBytes(values),
		},
		nil,
		0,
		0,
	)

	str := array.NewStringData(data)
	fmt.Println(str) // outputs: ["pear" "banana"]

	schema := arrow.NewSchema([]arrow.Field{
		{
			Name:     "string",
			Type:     arrow.BinaryTypes.String,
			Nullable: true,
		},
	}, nil)
	record := array.NewRecord(schema, []arrow.Array{str}, 2)

	var output bytes.Buffer
	writer := ipc.NewWriter(&output, ipc.WithSchema(schema))

	err := writer.Write(record)
	if err != nil {
		log.Fatal(err)
	}

	err = writer.Close()
	if err != nil {
		log.Fatal(err) 
	}

	reader, err := ipc.NewReader(bytes.NewReader(output.Bytes()), ipc.WithSchema(schema))
	if err != nil {
		log.Fatal(err)
	}

	reader.Next()
	if reader.Err() != nil {
		log.Fatal(reader.Err()) // string offsets out of bounds of data buffer
	}
}

```

### Component(s)

Go

**Comment by zeroshade** [comment] 2024-06-25 21:17
Sorry for the long delay here, I was at a conference and then things have been a bit busy. I can't promise *when* i'll be able to get to this, but I'll add it to my todo list. If you feel up to trying to fix it yourself, I'd be happy to review any PRs if you end up getting to it before me.

**Comment by notfilippo** [comment] 2024-06-26 07:26
I would be happy to open a fix PR but I first wanted to make sure this wasn't expected behaviour. The Arrow spec [says](https://arrow.apache.org/docs/format/Columnar.html#variable-size-binary-layout:~:text=When%20serializing%20this%20layout%2C%20we%20recommend%20normalizing%20the%20offsets%20to%20start%20at%200.) that:

> When serializing this layout, we recommend normalizing the offsets to start at 0.

Which opens the possibility for this kind of issue to arise.

Also when comparing the code of the Go and C++ implementation, the IPC writer seems to have 1:1 behaviour match between the two languages, so I would assume that issue also exists there.

**Comment by zeroshade** [comment] 2024-06-27 17:57
You're correct that this isn't expected behavior, likely due to this scenario being uncommon and nearly all cases I'm aware of normalize the offsets at 0. But in the general case your code *should* work, and it would make sense to update the C++ implementation to fix this too.

**Comment by joellubi** [comment] 2024-07-08 14:18
Thanks @notfilippo for the clear example. I've been able to adapt the code to a unit test that indeed fails with the error you indicated. The reproduction can be found in this draft PR: #43176.

I'll likely have time over the next week to get into the issue and will update that PR when the fix is added.

**Comment by joellubi** [comment] 2024-07-15 16:31
Issue resolved by pull request 43176
https://github.com/apache/arrow/pull/43176

**Closed by joellubi** 2024-07-15 16:31 UTC
Labels: Type: bug, Component: Go
