### ISSUE TITLE
zlib failure in PyArrow 0.11.0

### ISSUE THREAD

**Issue by amachanic** [apache/arrow#2756] opened 2018-10-14 16:57 UTC
The following produces an exception on PyArrow 0.11.0: "zlib deflate failed, output buffer too small"

It works fine on 0.10.0, so I assume this is a regression?

```
import io
import pyarrow
from pyarrow import parquet

tbl = pyarrow.Table.from_arrays([pyarrow.array(['abc', 'def'])], ['some_col'])

f = io.BytesIO()
parquet.write_table(tbl, f, compression='gzip')
```

**Comment by kszucs** [comment] 2018-10-14 19:07
Although I can't reproduce it, the error must come from [here](https://github.com/apache/arrow/blob/e0f70bbf9bc8eb909373abaaf0b4c9f50bc0a2d6/cpp/src/arrow/util/compression_zlib.cc#L195).

How did You install pyarrow? Which platform?
Could You please create a [JIRA](https://issues.apache.org/jira/projects/ARROW/issues) ticket instead?

**Comment by wesm** [comment] 2018-10-14 19:16
I think we are dynamically linking to zlib now in 0.11 so @amachanic could you let us know what other versions of zlib do you have installed on your system?

**Comment by amachanic** [comment] 2018-10-15 02:16
@kszucs I installed pyarrow via pip. I had initially tested this on Amazon Linux (which I guess is Red Hat). Just tested on a couple of other machines: CentOS 7, and Ubuntu 16.04, and the repro works (which is to say, throws an exception) on both. I also just tested on Windows 7, and the repro does NOT throw an exception there.

Happy to create a JIRA ticket.


@wesm: both the Amazon Linux and CentOS machines have zlib 1.2.7-17. On Ubuntu, looks like it's 1.2.8 -- but full disclosure, I'm not sure I checked properly there. And I'm not sure at all how to check on Windows.

**Comment by tsellers-r7** [comment] 2018-10-18 15:16
@amachanic It looks like the fix landed 2 days ago. Is there a projected date for when the code will be released and show up on PyPi?

Thanks.

**Comment by wesm** [comment] 2018-10-18 16:08
We need to release 0.11.1. I am going to work on that today; so reckon updated packages would be on PyPI within the next 96 hours or so

**Closed** 2018-10-18 16:08 UTC

**Comment by amachanic** [comment] 2018-10-18 16:39
@wesm many thanks!

**Comment by xhochy** [comment] 2018-10-27 13:50
The fix was uploaded on PyPI some days ago.
