### ISSUE TITLE
Inconsistent behavior of VectorSchemaRoot Slice

### ISSUE THREAD

**Issue by pribor** [apache/arrow#35615] opened 2023-05-16 11:44 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

The current behavior of VectorSchemaRoot slice isn't consistent. If the slice range includes the whole VectorSchemaRoot it is returned without increasing the ref count. 

e.g.
```
VectorSchemaRoot root = new VectorSchemaRoot(vectors);
VectorSchemaRoot slice = root.slice(0, root.getRowCount);
slice.close() // the original root is released

vs

VectorSchemaRoot root = new VectorSchemaRoot(vectors);
VectorSchemaRoot slice = root.slice(0, root.getRowCount - 1);
slice.close() // the original root remains as it is
```

### Component(s)

Java

**Comment by lidavidm** [comment] 2023-05-16 11:51
This was fixed by https://github.com/apache/arrow/pull/35476 for 13.0.0.

Duplicate of https://github.com/apache/arrow/issues/35275

**Closed by lidavidm** 2023-05-16 11:51 UTC
Labels: Type: bug, Component: Java

**Comment by pribor** [comment] 2023-05-16 12:02
Awesome, thanks!
