### ISSUE TITLE
Invalid file served by Artifactory

### ISSUE THREAD

**Issue by dejlek** [apache/arrow#40746] opened 2024-03-22 15:52 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

Today we started having an issue with particular file on JFrog's Artifactory server preventing us from building our software:

```
(venv) [dejan@server ~]$ wget https://apache.jfrog.io/artifactory/arrow/amazon-linux/2/x86_64/Packages/arrow12-acero-libs-12.0.1-1.amzn2.x86_64.rpm
--2024-03-22 15:44:35--  https://apache.jfrog.io/artifactory/arrow/amazon-linux/2/x86_64/Packages/arrow12-acero-libs-12.0.1-1.amzn2.x86_64.rpm
Resolving apache.jfrog.io (apache.jfrog.io)... 18.232.172.199, 3.95.117.170, 18.214.194.113
Connecting to apache.jfrog.io (apache.jfrog.io)|18.232.172.199|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://landing.jfrog.com/reactivate-server/apache [following]
--2024-03-22 15:44:35--  https://landing.jfrog.com/reactivate-server/apache
Resolving landing.jfrog.com (landing.jfrog.com)... 18.214.194.113, 18.232.172.199, 3.95.117.170
Connecting to landing.jfrog.com (landing.jfrog.com)|18.214.194.113|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11533 (11K) [text/html]
Saving to: ‘arrow12-acero-libs-12.0.1-1.amzn2.x86_64.rpm’

100%[=============================================================================================================================================================================================>] 11,533      --.-K/s   in 0s      

2024-03-22 15:44:35 (92.2 MB/s) - ‘arrow12-acero-libs-12.0.1-1.amzn2.x86_64.rpm’ saved [11533/11533]
```

Is file an RPM?
```
(venv) [dejan@server ~]$ file arrow12-acero-libs-12.0.1-1.amzn2.x86_64.rpm 
arrow12-acero-libs-12.0.1-1.amzn2.x86_64.rpm: HTML document, ASCII text, with very long lines
```
No, it is not
Check the content:
```
(venv) [dejan@server ~]$ head arrow12-acero-libs-12.0.1-1.amzn2.x86_64.rpm 
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.ico"><title>JFrog Landing</title><link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800&display=swap" rel="stylesheet"><script>VERSION = "2024.2.251";
      API_PROXY_URL = "https://landing-api.jfrog.com/api/v1/";
      API_PROXY_URL_V2 = "https://landing-api.jfrog.com/api/v2/";
      MYJFROG_UI_URL = "https://my.jfrog.com";
      COOKIES_DOMAIN = "jfrog.com";
      AWS_PROX_URL = "https://aws.amazon.com/marketplace/pp/B0819LTNJR";
      DRIFT_EMBED_ID = "gebxvrgwfyr7";
      GOOGLE_CLIENT_ID = "527996402582-i2kl20du99gjd8dnr3cce1a8ao0sgou7.apps.googleusercontent.com";
      PLATFORM_DOMAIN = "jfrog.io";
      CONNECT_DOMAIN = "https://connect.jfrog.io";
```

### Component(s)

Website

**Comment by assignUser** [comment] 2024-03-22 15:56
It's a know issue, sorry for the inconvenience. Duplicate of #40744

**Closed** 2024-03-22 15:56 UTC
Labels: Type: bug, Component: Website
