### ISSUE TITLE
unify_schema()

### ISSUE THREAD

**Issue by PoojaRavi1105** [apache/arrow#37897] opened 2023-09-27 07:31 UTC
### Describe the usage question you have. Please include as many useful details as  possible.

I am trying to merge multiple parquet files using pyarrow's unify_schema(). During schema evolution, the same field type has 2 different data type structures and the invocation to unify_schema() is failing. What is the best way to handle schema evolution in such cases?

### Component(s)

Parquet, Python

**Comment by AlenkaF** [comment] 2023-09-27 08:58
Duplicate of #37898.

**Closed by AlenkaF** 2023-09-27 08:58 UTC
Labels: Component: Parquet, Component: Python, Type: usage
