### ISSUE TITLE
Python Alpine and Pyarrow

### ISSUE THREAD

**Issue by sfc-gh-aivanou** [apache/arrow#43731] opened 2024-08-16 23:13 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

Does anyone know why `pip install pyarrow` does not work with `python:3.10-alpine` docker image?

E.g.  this simple image:
```
FROM python:3.10-alpine

RUN apk add build-base linux-headers
RUN pip install --no-cache-dir --upgrade pip
RUN pip install cmake
RUN pip install pyarrow

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]

```

Fails with

```
13.92       copying pyarrow/tests/data/feather/v0.17.0.version.2-compression.lz4.feather -> build/lib.linux-x86_64-cpython-310/pyarrow/tests/data/feather
13.92       running build_ext
13.92       creating /tmp/pip-install-x7hld2to/pyarrow_7d094121e229462db5f571453b46aa62/build/temp.linux-x86_64-cpython-310
13.92       -- Running cmake for PyArrow
13.92       cmake -DCMAKE_INSTALL_PREFIX=/tmp/pip-install-x7hld2to/pyarrow_7d094121e229462db5f571453b46aa62/build/lib.linux-x86_64-cpython-310/pyarrow -DPYTHON_EXECUTABLE=/usr/local/bin/python -DPython3_EXECUTABLE=/usr/local/bin/python -DPYARROW_CXXFLAGS= -DPYARROW_BUNDLE_ARROW_CPP=off -DPYARROW_BUNDLE_CYTHON_CPP=off -DPYARROW_GENERATE_COVERAGE=off -DCMAKE_BUILD_TYPE=release /tmp/pip-install-x7hld2to/pyarrow_7d094121e229462db5f571453b46aa62
13.92       Traceback (most recent call last):
13.92         File "/usr/local/bin/cmake", line 5, in <module>
13.92           from cmake import cmake
13.92       ModuleNotFoundError: No module named 'cmake'
13.92       error: command '/usr/local/bin/cmake' failed with exit code 1
13.92       [end of output]
```

### Component(s)

Developer Tools, Python

**Comment by assignUser** [comment] 2024-08-17 02:11
Duplicate of #39846.

Please see #18036, we don't publish musl wheels at the moment.
For building from source in docker see #39846.

**Closed by assignUser** 2024-08-17 02:11 UTC
Labels: Type: bug, Component: Python, Component: Developer Tools
