### ISSUE TITLE
[JAVA] arrow can not send listvector  issue

### ISSUE THREAD

**Issue by liaotian1005** [apache/arrow#4619] opened 2019-06-20 02:05 UTC
apache can not send VectorSchemaRoot data ,VectorSchemaRoot contain listvector .
use  VectorSchemaRoot.create(Flieds) api.
list write 3 position !  error message it is java.lang.IllegalArgumentException: not all nodes and buffers were consumed. nodes: [ArrowFieldNode [length=138, nullCount=0], ArrowFieldNode [length=138, nullCount=46], ArrowFieldNode [length=138, nullCount=115], ArrowFieldNode [length=138, nullCount=115]] buffers: [ArrowBuf[101], udle: [24 16..17], ArrowBuf[102], udle: [24 24..52], ArrowBuf[103], udle: [24 56..194], ArrowBuf[104], udle: [24 200..218], ArrowBuf[105], udle: [24 224..780], ArrowBuf[106], udle: [24 784..1550], ArrowBuf[107], udle: [24 1552..1570], ArrowBuf[108], udle: [24 1576..2128], ArrowBuf[109], udle: [24 2128..2146], ArrowBuf[110], udle: [24 2152..3256]]
	at org.apache.arrow.vector.VectorLoader.load(VectorLoader.java:64)
	at org.apache.arrow.vector.ipc.ArrowReader.loadRecordBatch(ArrowReader.java:219)

**Comment by emkornfield** [comment] 2019-06-20 08:37
Duplicate of #4620

**Closed** 2019-06-20 14:44 UTC
