### ISSUE TITLE
[C++][Python] write_csv / WriteCSV sometimes duplicates header

### ISSUE THREAD

**Issue by mattaubury** [apache/arrow#37903] opened 2023-09-27 13:10 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

(Tested in pyarrow-13.0.0, Linux x64)

`WriteCSV` / `write_csv` can print out a duplicate header (and sometimes other junk) when one or more empty batches makes up a table.

Minimal example:
```
>>> import sys
>>> import pyarrow as pa
>>> import pyarrow.csv as csv

>>> t1 = pa.table([pa.array([], pa.int64())], "x")
>>> t2 = pa.table([pa.array([1, 2, 3], pa.int64())], "x")
>>> csv.write_csv(pa.concat_tables([t1, t2]), sys.stdout.buffer)
"x"
"x"
1
2
3
```
I expect to only see a single "x" header.

From C++, I've also seen WriteCSV output junk before the header (seemingly part of the schema).

### Component(s)

C++, Python

**Comment by adityush007** [comment] 2023-10-10 05:33
Please assign me this Issue. I would like to work on it.

**Comment by graydenshand** [comment] 2024-02-13 17:33
I believe this issue is a duplicate of https://github.com/apache/arrow/issues/36889

**Comment by pitrou** [comment] 2024-09-18 14:15
Closing as duplicate of https://github.com/apache/arrow/issues/36889

**Closed by pitrou** 2024-09-18 14:15 UTC
Labels: Type: bug, Component: C++, Component: Python
