### ISSUE TITLE
[C++][CI] Boost-related compilation error on macOS ARM

### ISSUE THREAD

**Issue by pitrou** [apache/arrow#43777] opened 2024-08-21 12:34 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

These build failures have appeared very recently, see example:
https://github.com/apache/arrow/actions/runs/10481257647/job/29030430952

They seem related to Boost process.

### Component(s)

C++, Continuous Integration

**Comment by kou** [comment] 2024-08-21 21:55
This must be the same problem as #43746 because it also uses Boost 1.86: https://github.com/apache/arrow/actions/runs/10481257647/job/29030430952#step:12:225

```text
-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.86.0/BoostConfig.cmake (found suitable version "1.86.0", minimum required is "1.64") found components: system filesystem
```

#43766 will fix this too.

I close this as duplicate of #43746.

**Closed by kou** 2024-08-21 21:55 UTC
Labels: Type: bug, Component: C++, Component: Continuous Integration
