### ISSUE TITLE
[Docs][Format] Document Run-Length encoding in Arrow columnar format

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32106] opened 2022-06-07 13:11 UTC
**Reporter**: [Tobias Zagorni](https://issues.apache.org/jira/browse/ARROW-16773) / @zagto
**Assignee**: [Tobias Zagorni](https://issues.apache.org/jira/browse/ARROW-16773) / @zagto
#### PRs and other links:
- [GitHub Pull Request #13333](https://github.com/apache/arrow/pull/13333)

<sub>**Note**: *This issue was originally created as [ARROW-16773](https://issues.apache.org/jira/browse/ARROW-16773). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment] 2024-03-12 10:06
The PR addressing this was closed because the changes were incorporated in PR https://github.com/apache/arrow/pull/14176, so closing as duplicate of https://github.com/apache/arrow/issues/32115

**Closed by jorisvandenbossche** 2024-03-12 10:06 UTC
Labels: Component: Documentation, Component: Format, Type: task
