### ISSUE TITLE
[R] Function create_package_with_all_dependencies fails

### ISSUE THREAD

**Issue by obruck** [apache/arrow#15202] opened 2023-01-05 14:05 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

**Platform** R
**R version** 3.5.1
**Arrow version** arrow_10.0.1

The `create_package_with_all_dependencies` function fails with the following error message

`Error in download.file("https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz",  : `
`  cannot open URL 'https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz'`
`In addition: Warning message:`
`In download.file("https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz",  :`
` Show Traceback`
` Rerun with Debug`
` Error in download.file("https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz",  : `
 ` cannot open URL 'https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz'`

The solution is to run the following command before to avoid missing CA certificates of https-links
`options(download.file.method="curl", download.file.extra="-k -L")`

### Component(s)

R

**Comment by thisisnic** [comment] 2023-03-30 12:22
Thanks for reporting this @obruck, and sorry for the delay in responding.  

From what you've said, it looks like the issue was caused by that particular site having a missing CA certificate.  I'm disinclined to set the option you mention there on the behalf of the user, and your workaround seems like a good one.  I'm wondering if we should at least set the `download.file()` output to print status messages to make it easier to diagnose the problem.

**Comment by obruck** [comment] 2023-03-30 13:04
No worries. Might be indeed that not R users will have the similar with that, but looks like the issue cannot be fixed by configuring the RStudio settings. There could be a prompt asking whether it is ok to download files also from sites with missing certificates or indeed an output to print the messages. Whatever you feel is the best solution!

**Comment by assignUser** [comment] 2023-04-12 01:11
As discussed in #34799 this is most likely caused by an outdated CA bundle on your system/the old R version. As the workaround is [insecure](https://curl.se/docs/manpage.html#-k) it is not somethign the arrow package should set, so I am closing the issue.

This issue will work as documentation for the workaround (gh issues have quite good seo for problem searches in my experience) so thank you for your report and workaround @obruck !

**Closed by assignUser** 2023-04-12 01:11 UTC
Labels: Type: bug, Component: R
