### ISSUE TITLE
[C#] ArrowArrayConcatenator doesn't handle non-zero offsets

### ISSUE THREAD

**Issue by adamreeve** [apache/arrow#41164] opened 2024-04-12 03:39 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

Example unit test to reproduce:

```c#
[Fact]
public void TestConcatenateSlicedArrays()
{
    Int32Array array0 = new Int32Array.Builder()
        .Append(new []{0, 1, 2})
        .AppendNull()
        .Append(new []{3, 4})
        .Build();
    Int32Array array1 = new Int32Array.Builder()
        .Append(new []{5, 6})
        .AppendNull()
        .Append(new [] {7, 8, 9})
        .Build();

    var concatenated = ArrowArrayConcatenator.Concatenate(new[]
    {
        ArrowArrayFactory.Slice(array0, 2, 3),
        ArrowArrayFactory.Slice(array1, 2, 3),
    });

    var expected = new Int32Array.Builder()
        .Append(2).AppendNull().Append(3)
        .AppendNull().Append(new[] { 7, 8 })
        .Build();

    Assert.Equal(expected, (IReadOnlyList<int?>)concatenated);
}
```

This fails with:
```
Assert.Equal() Failure: Collections differ
           ↓ (pos 0)
Expected: [2, null, 3, null, 7, ···]
Actual:   [0, 1, 2, 5, 6, ···]
           ↑ (pos 0)
```

### Component(s)

C#

**Comment by CurtHagenlocher** [comment] 2024-04-17 04:03
Issue resolved by pull request 41245
https://github.com/apache/arrow/pull/41245

**Closed by CurtHagenlocher** 2024-04-17 04:03 UTC
Labels: Type: bug, Component: C#

**Comment by CurtHagenlocher** [comment] 2024-05-29 13:53
> Can this be backported to a bugfix `16.x` release?

The Arrow release process is fairly labor-intensive, so bugfix releases are typically reserved for regressions. This fix is for a longstanding bug and not a regression, so on its own it wouldn't be a candidate for a point release. If it turns out that we need a 16.2 release for some other reason, I'll investigate the possibility of porting this set of fixes alongside it.

The next regular release will be roughly at the beginning of August.
