### ISSUE TITLE
[Python] csv does not work with a cedilla delimiter

### ISSUE THREAD

**Issue by rkarthik29** [apache/arrow#39287] opened 2023-12-18 21:20 UTC
### Describe the bug, including details regarding any error messages, version, and platform.

we are trying to parse a CSV file that has a cedilla \x03 delimiter. When passing this to pyarrow.csv.read_csv, the parse complains that the delimiter \x03 is not a valid ascii. Is there a way around this issue ?

ile ~/miniconda3/envs/sandbox/lib/python3.11/site-packages/pyarrow/_csv.pyx:422, in pyarrow._csv.ParseOptions.__init__()

File ~/miniconda3/envs/sandbox/lib/python3.11/site-packages/pyarrow/_csv.pyx:445, in pyarrow._csv.ParseOptions.delimiter.__set__()

File ~/miniconda3/envs/sandbox/lib/python3.11/site-packages/pyarrow/_csv.pyx:46, in pyarrow._csv._single_char()

ValueError: Expecting an ASCII character

i  get the above error if i use the character as delim "Ç"

but if i use \x03 , the data is read, but it is not parsed into columns.

i also tried "Ç".encode(ascii) and i get an error that the ascii code \xc7 is not valid. I tried chr(199). Nothing worked. Could anybody guide me in the right direction here. Dont want to use pandas 

### Component(s)

Python

**Comment by AlenkaF** [comment] 2023-12-19 08:20
I think the issue here is that letter `C` with cedilla is not included in the main ASCII Table and I am not sure how to work around it.

I am not sure pandas will work here either.

**Comment by rkarthik29** [comment] 2024-01-02 18:24
@AlenkaF It works with pandas if we use the unicode value \x03 for the cedilla as our seperator.

**Comment by jorisvandenbossche** [comment] 2024-01-08 16:50
There is currently no way around this: arrow only supports single ASCII characters as separator at the moment.

Related issues: https://github.com/apache/arrow/issues/32432, https://github.com/apache/arrow/issues/26411

Going to close this as duplicate of those other issues.

**Closed by jorisvandenbossche** 2024-01-08 16:50 UTC
Labels: Type: bug, Component: Python
