### ISSUE TITLE
Advise how to resolve table concatenation for differing types: i.e. int16 vs int64 

### ISSUE THREAD

**Issue by ncgl-syngenta** [apache/arrow#37068] opened 2023-08-08 18:19 UTC
### Describe the usage question you have. Please include as many useful details as  possible.

`pyarrow.lib.ArrowInvalid: Unable to merge: Field M_SECTION_ID has incompatible types: int16 vs int64`

My team is trying to combine parquet files on the fly, using pyarrow. Sometimes we run into this issue because we've decided upstream that we can leverage the smaller datatype size. What is the recommended way to get around errors like this? I would expect we could concatenate the above example since they are both integers.

### Component(s)

Parquet, Python

**Comment by lidavidm** [comment] 2023-08-08 18:22
Duplicate of #30245 #36845

**Comment by ncgl-syngenta** [comment] 2023-08-08 19:33
Thanks for the fast response @lidavidm

**Closed** 2023-11-19 08:03 UTC
Labels: Component: Parquet, Component: Python, Type: usage
