### ISSUE TITLE
[C++][Python] Basic conversion of RecordBatch to Arrow Tensor - add support for row-major

### ISSUE THREAD

**Issue by AlenkaF** [apache/arrow#40866] opened 2024-03-28 12:44 UTC
### Describe the enhancement requested

This issue is a part of https://github.com/apache/arrow/issues/40058 and adds an option to construct a row-major `Tensor` from a `RecordBatch` which is a layout used most often when working with tensors.

### Component(s)

C++, Python

**Comment by jorisvandenbossche** [comment] 2024-04-10 10:15
Although this is a new feature and not a bug fix, it is changing the behaviour of a newly introduced feature for 16.0, and therefore I would propose to include it for 16.0 as well, to avoid that we directly make a breaking change in the new feature in the next release.

**Comment by jorisvandenbossche** [comment] 2024-04-10 10:15
Issue resolved by pull request 40867
https://github.com/apache/arrow/pull/40867

**Closed by jorisvandenbossche** 2024-04-10 10:15 UTC
Labels: Type: enhancement, Component: C++, Component: Python
